-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    img_V_val_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_V_val_0_V_full_n : IN STD_LOGIC;
    img_V_val_0_V_write : OUT STD_LOGIC;
    img_V_val_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_V_val_1_V_full_n : IN STD_LOGIC;
    img_V_val_1_V_write : OUT STD_LOGIC;
    img_V_val_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_V_val_2_V_full_n : IN STD_LOGIC;
    img_V_val_2_V_write : OUT STD_LOGIC;
    HwReg_height_cast5_loc_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    HwReg_height_cast5_loc_empty_n : IN STD_LOGIC;
    HwReg_height_cast5_loc_read : OUT STD_LOGIC;
    HwReg_width_cast6_loc_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    HwReg_width_cast6_loc_empty_n : IN STD_LOGIC;
    HwReg_width_cast6_loc_read : OUT STD_LOGIC;
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    HwReg_height_cast5_loc_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    HwReg_height_cast5_loc_out_full_n : IN STD_LOGIC;
    HwReg_height_cast5_loc_out_write : OUT STD_LOGIC;
    HwReg_width_cast6_loc_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    HwReg_width_cast6_loc_out_full_n : IN STD_LOGIC;
    HwReg_width_cast6_loc_out_write : OUT STD_LOGIC );
end;


architecture behav of design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp2_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal AXI_video_strm_V_data_V_0_data_out : STD_LOGIC_VECTOR (23 downto 0);
    signal AXI_video_strm_V_data_V_0_vld_in : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_vld_out : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_ack_in : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_ack_out : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_payload_A : STD_LOGIC_VECTOR (23 downto 0);
    signal AXI_video_strm_V_data_V_0_payload_B : STD_LOGIC_VECTOR (23 downto 0);
    signal AXI_video_strm_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal AXI_video_strm_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal AXI_video_strm_V_data_V_0_sel : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_load_A : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_load_B : STD_LOGIC;
    signal AXI_video_strm_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AXI_video_strm_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_user_V_0_vld_in : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_vld_out : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_ack_in : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_ack_out : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_user_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_user_V_0_sel_rd : STD_LOGIC := '0';
    signal AXI_video_strm_V_user_V_0_sel_wr : STD_LOGIC := '0';
    signal AXI_video_strm_V_user_V_0_sel : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_load_A : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_load_B : STD_LOGIC;
    signal AXI_video_strm_V_user_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AXI_video_strm_V_user_V_0_state_cmp_full : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_last_V_0_vld_in : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_vld_out : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_ack_in : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_ack_out : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_last_V_0_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal AXI_video_strm_V_last_V_0_sel_rd : STD_LOGIC := '0';
    signal AXI_video_strm_V_last_V_0_sel_wr : STD_LOGIC := '0';
    signal AXI_video_strm_V_last_V_0_sel : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_load_A : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_load_B : STD_LOGIC;
    signal AXI_video_strm_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal AXI_video_strm_V_last_V_0_state_cmp_full : STD_LOGIC;
    signal AXI_video_strm_V_dest_V_0_vld_in : STD_LOGIC;
    signal AXI_video_strm_V_dest_V_0_ack_out : STD_LOGIC;
    signal AXI_video_strm_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal s_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal exitcond6_i_i_reg_588 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_reg_597 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp2_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp2_stage0 : signal is "none";
    signal ap_enable_reg_pp2_iter1 : STD_LOGIC := '0';
    signal ap_block_pp2_stage0 : BOOLEAN;
    signal eol_2_i_i_reg_364 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_V_val_0_V_blk_n : STD_LOGIC;
    signal img_V_val_1_V_blk_n : STD_LOGIC;
    signal img_V_val_2_V_blk_n : STD_LOGIC;
    signal HwReg_height_cast5_loc_blk_n : STD_LOGIC;
    signal HwReg_width_cast6_loc_blk_n : STD_LOGIC;
    signal HwReg_height_cast5_loc_out_blk_n : STD_LOGIC;
    signal HwReg_width_cast6_loc_out_blk_n : STD_LOGIC;
    signal eol_i_i_reg_294 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_i_i_reg_306 : STD_LOGIC_VECTOR (11 downto 0);
    signal eol_reg_317 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_i_i_reg_328 : STD_LOGIC_VECTOR (23 downto 0);
    signal axi_last_V_3_i_i_reg_375 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_3_i_i_reg_387 : STD_LOGIC_VECTOR (23 downto 0);
    signal HwReg_width_cast6_lo_reg_527 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal Height_cast_i_i_fu_409_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal Height_cast_i_i_reg_532 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_413_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_419_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal grp_reg_unsigned_short_s_fu_413_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i_i_reg_542 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_reg_unsigned_short_s_fu_419_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i_i_230_reg_547 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_data_V_reg_552 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_last_V_reg_560 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_reg_572 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal exitcond5_i_i_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_fu_448_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_reg_583 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond6_i_i_fu_454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state6_pp1_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op80_read_state7 : BOOLEAN;
    signal img_V_val_0_V1_status : STD_LOGIC;
    signal ap_block_state7_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal j_fu_459_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal brmerge_i_i_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9_pp2_stage0_iter0 : BOOLEAN;
    signal ap_block_state10_pp2_stage0_iter1 : BOOLEAN;
    signal ap_block_pp2_stage0_11001 : BOOLEAN;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp2_iter0 : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_block_pp2_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_eol_2_i_i_phi_fu_367_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_413_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_413_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_413_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_419_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_419_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_419_ap_ready : STD_LOGIC;
    signal axi_last_V1_i_i_reg_263 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal axi_data_V1_i_i_reg_273 : STD_LOGIC_VECTOR (23 downto 0);
    signal i_i_i_reg_283 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_eol_i_i_phi_fu_298_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_Val2_s_phi_fu_356_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter1_p_Val2_s_reg_352 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call21 : BOOLEAN;
    signal ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call22 : BOOLEAN;
    signal img_V_val_0_V1_update : STD_LOGIC;
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal sof_1_i_i_fu_194 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_cast_i_i_fu_439_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal pix_val_2_V_fu_493_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_0_V_fu_479_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_val_1_V_8_fu_489_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_fu_425_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal ap_idle_pp2 : STD_LOGIC;
    signal ap_enable_pp2 : STD_LOGIC;
    signal ap_condition_511 : BOOLEAN;

    component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_r : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_reg_unsigned_short_s_fu_413 : component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_413_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_413_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_413_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_413_ap_ready,
        in_r => Height_cast_i_i_reg_532,
        ap_return => grp_reg_unsigned_short_s_fu_413_ap_return);

    grp_reg_unsigned_short_s_fu_419 : component design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_419_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_419_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_419_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_419_ap_ready,
        in_r => HwReg_width_cast6_lo_reg_527,
        ap_return => grp_reg_unsigned_short_s_fu_419_ap_return);





    AXI_video_strm_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_data_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_vld_out))) then 
                                        AXI_video_strm_V_data_V_0_sel_rd <= not(AXI_video_strm_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_data_V_0_ack_in) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_vld_in))) then 
                                        AXI_video_strm_V_data_V_0_sel_wr <= not(AXI_video_strm_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((AXI_video_strm_V_data_V_0_state = ap_const_lv2_2) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_in)) or ((AXI_video_strm_V_data_V_0_state = ap_const_lv2_3) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_ack_out)))) then 
                    AXI_video_strm_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((AXI_video_strm_V_data_V_0_state = ap_const_lv2_1) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_ack_out)) or ((AXI_video_strm_V_data_V_0_state = ap_const_lv2_3) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_vld_in)))) then 
                    AXI_video_strm_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_ack_out))) and not(((ap_const_logic_0 = AXI_video_strm_V_data_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_vld_in))) and (AXI_video_strm_V_data_V_0_state = ap_const_lv2_3)) or ((AXI_video_strm_V_data_V_0_state = ap_const_lv2_1) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_ack_out)) or ((AXI_video_strm_V_data_V_0_state = ap_const_lv2_2) and (ap_const_logic_1 = AXI_video_strm_V_data_V_0_vld_in)))) then 
                    AXI_video_strm_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    AXI_video_strm_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_dest_V_0_vld_in)) or ((ap_const_lv2_3 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_dest_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_ack_out)))) then 
                    AXI_video_strm_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_dest_V_0_ack_out)) or ((ap_const_lv2_3 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_dest_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_vld_in)))) then 
                    AXI_video_strm_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AXI_video_strm_V_dest_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_ack_out))) and not(((ap_const_logic_0 = AXI_video_strm_V_dest_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_vld_in))) and (ap_const_lv2_3 = AXI_video_strm_V_dest_V_0_state)) or ((ap_const_lv2_1 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_ack_out)) or ((ap_const_lv2_2 = AXI_video_strm_V_dest_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_dest_V_0_vld_in)))) then 
                    AXI_video_strm_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    AXI_video_strm_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_last_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_last_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_last_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_vld_out))) then 
                                        AXI_video_strm_V_last_V_0_sel_rd <= not(AXI_video_strm_V_last_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_last_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_last_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_last_V_0_ack_in) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_vld_in))) then 
                                        AXI_video_strm_V_last_V_0_sel_wr <= not(AXI_video_strm_V_last_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_last_V_0_vld_in)) or ((ap_const_lv2_3 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_last_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_ack_out)))) then 
                    AXI_video_strm_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_last_V_0_ack_out)) or ((ap_const_lv2_3 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_last_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_vld_in)))) then 
                    AXI_video_strm_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AXI_video_strm_V_last_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_ack_out))) and not(((ap_const_logic_0 = AXI_video_strm_V_last_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_vld_in))) and (ap_const_lv2_3 = AXI_video_strm_V_last_V_0_state)) or ((ap_const_lv2_1 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_ack_out)) or ((ap_const_lv2_2 = AXI_video_strm_V_last_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_last_V_0_vld_in)))) then 
                    AXI_video_strm_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    AXI_video_strm_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_user_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_user_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_user_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_vld_out))) then 
                                        AXI_video_strm_V_user_V_0_sel_rd <= not(AXI_video_strm_V_user_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_user_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_user_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = AXI_video_strm_V_user_V_0_ack_in) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_vld_in))) then 
                                        AXI_video_strm_V_user_V_0_sel_wr <= not(AXI_video_strm_V_user_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    AXI_video_strm_V_user_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                AXI_video_strm_V_user_V_0_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_user_V_0_vld_in)) or ((ap_const_lv2_3 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_user_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_ack_out)))) then 
                    AXI_video_strm_V_user_V_0_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_user_V_0_ack_out)) or ((ap_const_lv2_3 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_0 = AXI_video_strm_V_user_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_vld_in)))) then 
                    AXI_video_strm_V_user_V_0_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = AXI_video_strm_V_user_V_0_vld_in) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_ack_out))) and not(((ap_const_logic_0 = AXI_video_strm_V_user_V_0_ack_out) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_vld_in))) and (ap_const_lv2_3 = AXI_video_strm_V_user_V_0_state)) or ((ap_const_lv2_1 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_ack_out)) or ((ap_const_lv2_2 = AXI_video_strm_V_user_V_0_state) and (ap_const_logic_1 = AXI_video_strm_V_user_V_0_vld_in)))) then 
                    AXI_video_strm_V_user_V_0_state <= ap_const_lv2_3;
                else 
                    AXI_video_strm_V_user_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_lv1_1 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_block_pp1_stage0_subdone = ap_const_boolean_0) and (ap_const_lv1_1 = exitcond6_i_i_fu_454_p2) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if ((ap_block_pp1_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
            else
                if (((ap_block_pp2_stage0_subdone = ap_const_boolean_0) and (ap_const_lv1_1 = ap_phi_mux_eol_2_i_i_phi_fu_367_p4) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_enable_reg_pp2_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp2_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
            else
                if ((ap_block_pp2_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_enable_reg_pp2_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= ap_const_logic_0;
            else
                if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_reg_unsigned_short_s_fu_413_ap_ready)) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= ap_const_logic_0;
            else
                if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_reg_unsigned_short_s_fu_419_ap_ready)) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V1_i_i_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_data_V1_i_i_reg_273 <= tmp_data_V_reg_552;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                axi_data_V1_i_i_reg_273 <= axi_data_V_3_i_i_reg_387;
            end if; 
        end if;
    end process;

    axi_data_V_1_i_i_reg_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                axi_data_V_1_i_i_reg_328 <= ap_phi_mux_p_Val2_s_phi_fu_356_p4;
            elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                axi_data_V_1_i_i_reg_328 <= axi_data_V1_i_i_reg_273;
            end if; 
        end if;
    end process;

    axi_data_V_3_i_i_reg_387_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                axi_data_V_3_i_i_reg_387 <= axi_data_V_1_i_i_reg_328;
            elsif (((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                axi_data_V_3_i_i_reg_387 <= AXI_video_strm_V_data_V_0_data_out;
            end if; 
        end if;
    end process;

    axi_last_V1_i_i_reg_263_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                axi_last_V1_i_i_reg_263 <= tmp_last_V_reg_560;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                axi_last_V1_i_i_reg_263 <= axi_last_V_3_i_i_reg_375;
            end if; 
        end if;
    end process;

    axi_last_V_3_i_i_reg_375_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                axi_last_V_3_i_i_reg_375 <= eol_reg_317;
            elsif (((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                axi_last_V_3_i_i_reg_375 <= AXI_video_strm_V_last_V_0_data_out;
            end if; 
        end if;
    end process;

    eol_2_i_i_reg_364_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                eol_2_i_i_reg_364 <= eol_i_i_reg_294;
            elsif (((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
                eol_2_i_i_reg_364 <= AXI_video_strm_V_last_V_0_data_out;
            end if; 
        end if;
    end process;

    eol_i_i_reg_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                eol_i_i_reg_294 <= ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
            elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                eol_i_i_reg_294 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    eol_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                eol_reg_317 <= ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
            elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                eol_reg_317 <= axi_last_V1_i_i_reg_263;
            end if; 
        end if;
    end process;

    i_i_i_reg_283_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_i_i_reg_283 <= ap_const_lv11_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                i_i_i_reg_283 <= i_reg_583;
            end if; 
        end if;
    end process;

    j_i_i_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_fu_454_p2) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                j_i_i_reg_306 <= j_fu_459_p2;
            elsif (((ap_const_lv1_0 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_i_i_reg_306 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    sof_1_i_i_fu_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_fu_454_p2) and (ap_const_logic_1 = ap_enable_reg_pp1_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
                sof_1_i_i_fu_194 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                sof_1_i_i_fu_194 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_data_V_0_load_A)) then
                AXI_video_strm_V_data_V_0_payload_A <= s_axis_video_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_data_V_0_load_B)) then
                AXI_video_strm_V_data_V_0_payload_B <= s_axis_video_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_last_V_0_load_A)) then
                AXI_video_strm_V_last_V_0_payload_A <= s_axis_video_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_last_V_0_load_B)) then
                AXI_video_strm_V_last_V_0_payload_B <= s_axis_video_TLAST;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_user_V_0_load_A)) then
                AXI_video_strm_V_user_V_0_payload_A <= s_axis_video_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = AXI_video_strm_V_user_V_0_load_B)) then
                AXI_video_strm_V_user_V_0_payload_B <= s_axis_video_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    Height_cast_i_i_reg_532(10 downto 0) <= Height_cast_i_i_fu_409_p1(10 downto 0);
                HwReg_width_cast6_lo_reg_527 <= HwReg_width_cast6_loc_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_fu_454_p2) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                brmerge_i_i_reg_597 <= brmerge_i_i_fu_468_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                exitcond6_i_i_reg_588 <= exitcond6_i_i_fu_454_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_reg_583 <= i_fu_448_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sel_tmp2_reg_572 <= sel_tmp2_fu_429_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_reg_552 <= AXI_video_strm_V_data_V_0_data_out;
                tmp_last_V_reg_560 <= AXI_video_strm_V_last_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_state2_on_subcall_done = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_i_i_230_reg_547 <= grp_reg_unsigned_short_s_fu_419_ap_return;
                tmp_i_i_reg_542 <= grp_reg_unsigned_short_s_fu_413_ap_return;
            end if;
        end if;
    end process;
    Height_cast_i_i_reg_532(11) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, AXI_video_strm_V_data_V_0_vld_out, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, exitcond5_i_i_fu_443_p2, ap_CS_fsm_state5, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0_subdone, ap_enable_reg_pp2_iter0, ap_block_pp2_stage0_subdone, tmp_user_V_fu_425_p1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_block_state2_on_subcall_done = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_lv1_0 = tmp_user_V_fu_425_p1) and (AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_const_lv1_1 = tmp_user_V_fu_425_p1) and (AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_lv1_1 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_block_pp1_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_block_pp1_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
            when ap_ST_fsm_pp2_stage0 => 
                if (not(((ap_block_pp2_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                elsif (((ap_block_pp2_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp2_iter0 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp2_stage0;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    AXI_video_strm_V_data_V_0_ack_in <= AXI_video_strm_V_data_V_0_state(1);

    AXI_video_strm_V_data_V_0_ack_out_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364, ap_predicate_op80_read_state7, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001)
    begin
        if ((((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_boolean_1 = ap_predicate_op80_read_state7) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            AXI_video_strm_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            AXI_video_strm_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AXI_video_strm_V_data_V_0_data_out_assign_proc : process(AXI_video_strm_V_data_V_0_payload_A, AXI_video_strm_V_data_V_0_payload_B, AXI_video_strm_V_data_V_0_sel)
    begin
        if ((ap_const_logic_1 = AXI_video_strm_V_data_V_0_sel)) then 
            AXI_video_strm_V_data_V_0_data_out <= AXI_video_strm_V_data_V_0_payload_B;
        else 
            AXI_video_strm_V_data_V_0_data_out <= AXI_video_strm_V_data_V_0_payload_A;
        end if; 
    end process;

    AXI_video_strm_V_data_V_0_load_A <= (not(AXI_video_strm_V_data_V_0_sel_wr) and AXI_video_strm_V_data_V_0_state_cmp_full);
    AXI_video_strm_V_data_V_0_load_B <= (AXI_video_strm_V_data_V_0_state_cmp_full and AXI_video_strm_V_data_V_0_sel_wr);
    AXI_video_strm_V_data_V_0_sel <= AXI_video_strm_V_data_V_0_sel_rd;
    AXI_video_strm_V_data_V_0_state_cmp_full <= '0' when (AXI_video_strm_V_data_V_0_state = ap_const_lv2_1) else '1';
    AXI_video_strm_V_data_V_0_vld_in <= s_axis_video_TVALID;
    AXI_video_strm_V_data_V_0_vld_out <= AXI_video_strm_V_data_V_0_state(0);

    AXI_video_strm_V_dest_V_0_ack_out_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364, ap_predicate_op80_read_state7, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001)
    begin
        if ((((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_boolean_1 = ap_predicate_op80_read_state7) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            AXI_video_strm_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            AXI_video_strm_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    AXI_video_strm_V_dest_V_0_vld_in <= s_axis_video_TVALID;
    AXI_video_strm_V_last_V_0_ack_in <= AXI_video_strm_V_last_V_0_state(1);

    AXI_video_strm_V_last_V_0_ack_out_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364, ap_predicate_op80_read_state7, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001)
    begin
        if ((((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_boolean_1 = ap_predicate_op80_read_state7) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            AXI_video_strm_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            AXI_video_strm_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AXI_video_strm_V_last_V_0_data_out_assign_proc : process(AXI_video_strm_V_last_V_0_payload_A, AXI_video_strm_V_last_V_0_payload_B, AXI_video_strm_V_last_V_0_sel)
    begin
        if ((ap_const_logic_1 = AXI_video_strm_V_last_V_0_sel)) then 
            AXI_video_strm_V_last_V_0_data_out <= AXI_video_strm_V_last_V_0_payload_B;
        else 
            AXI_video_strm_V_last_V_0_data_out <= AXI_video_strm_V_last_V_0_payload_A;
        end if; 
    end process;

    AXI_video_strm_V_last_V_0_load_A <= (not(AXI_video_strm_V_last_V_0_sel_wr) and AXI_video_strm_V_last_V_0_state_cmp_full);
    AXI_video_strm_V_last_V_0_load_B <= (AXI_video_strm_V_last_V_0_state_cmp_full and AXI_video_strm_V_last_V_0_sel_wr);
    AXI_video_strm_V_last_V_0_sel <= AXI_video_strm_V_last_V_0_sel_rd;
    AXI_video_strm_V_last_V_0_state_cmp_full <= '0' when (AXI_video_strm_V_last_V_0_state = ap_const_lv2_1) else '1';
    AXI_video_strm_V_last_V_0_vld_in <= s_axis_video_TVALID;
    AXI_video_strm_V_last_V_0_vld_out <= AXI_video_strm_V_last_V_0_state(0);
    AXI_video_strm_V_user_V_0_ack_in <= AXI_video_strm_V_user_V_0_state(1);

    AXI_video_strm_V_user_V_0_ack_out_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364, ap_predicate_op80_read_state7, ap_block_pp1_stage0_11001, ap_block_pp2_stage0_11001)
    begin
        if ((((ap_block_pp2_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_boolean_1 = ap_predicate_op80_read_state7) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)) or ((AXI_video_strm_V_data_V_0_vld_out = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            AXI_video_strm_V_user_V_0_ack_out <= ap_const_logic_1;
        else 
            AXI_video_strm_V_user_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    AXI_video_strm_V_user_V_0_data_out_assign_proc : process(AXI_video_strm_V_user_V_0_payload_A, AXI_video_strm_V_user_V_0_payload_B, AXI_video_strm_V_user_V_0_sel)
    begin
        if ((ap_const_logic_1 = AXI_video_strm_V_user_V_0_sel)) then 
            AXI_video_strm_V_user_V_0_data_out <= AXI_video_strm_V_user_V_0_payload_B;
        else 
            AXI_video_strm_V_user_V_0_data_out <= AXI_video_strm_V_user_V_0_payload_A;
        end if; 
    end process;

    AXI_video_strm_V_user_V_0_load_A <= (not(AXI_video_strm_V_user_V_0_sel_wr) and AXI_video_strm_V_user_V_0_state_cmp_full);
    AXI_video_strm_V_user_V_0_load_B <= (AXI_video_strm_V_user_V_0_state_cmp_full and AXI_video_strm_V_user_V_0_sel_wr);
    AXI_video_strm_V_user_V_0_sel <= AXI_video_strm_V_user_V_0_sel_rd;
    AXI_video_strm_V_user_V_0_state_cmp_full <= '0' when (AXI_video_strm_V_user_V_0_state = ap_const_lv2_1) else '1';
    AXI_video_strm_V_user_V_0_vld_in <= s_axis_video_TVALID;
    AXI_video_strm_V_user_V_0_vld_out <= AXI_video_strm_V_user_V_0_state(0);
    Height_cast_i_i_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(HwReg_height_cast5_loc_dout),12));

    HwReg_height_cast5_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_empty_n)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_cast5_loc_blk_n <= HwReg_height_cast5_loc_empty_n;
        else 
            HwReg_height_cast5_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_height_cast5_loc_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_cast5_loc_out_blk_n <= HwReg_height_cast5_loc_out_full_n;
        else 
            HwReg_height_cast5_loc_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_height_cast5_loc_out_din <= HwReg_height_cast5_loc_dout;

    HwReg_height_cast5_loc_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_cast5_loc_out_write <= ap_const_logic_1;
        else 
            HwReg_height_cast5_loc_out_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_height_cast5_loc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_height_cast5_loc_read <= ap_const_logic_1;
        else 
            HwReg_height_cast5_loc_read <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_width_cast6_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_width_cast6_loc_empty_n)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_cast6_loc_blk_n <= HwReg_width_cast6_loc_empty_n;
        else 
            HwReg_width_cast6_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_width_cast6_loc_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_width_cast6_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_cast6_loc_out_blk_n <= HwReg_width_cast6_loc_out_full_n;
        else 
            HwReg_width_cast6_loc_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_width_cast6_loc_out_din <= HwReg_width_cast6_loc_dout;

    HwReg_width_cast6_loc_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_cast6_loc_out_write <= ap_const_logic_1;
        else 
            HwReg_width_cast6_loc_out_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_width_cast6_loc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_width_cast6_loc_read <= ap_const_logic_1;
        else 
            HwReg_width_cast6_loc_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(5);
    ap_CS_fsm_pp2_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(8);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_enable_reg_pp1_iter1, exitcond6_i_i_reg_588, ap_predicate_op80_read_state7, img_V_val_0_V1_status)
    begin
                ap_block_pp1_stage0_01001 <= ((ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (((ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_boolean_1 = ap_predicate_op80_read_state7)) or ((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_0 = img_V_val_0_V1_status))));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_enable_reg_pp1_iter1, exitcond6_i_i_reg_588, ap_predicate_op80_read_state7, img_V_val_0_V1_status)
    begin
                ap_block_pp1_stage0_11001 <= ((ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (((ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_boolean_1 = ap_predicate_op80_read_state7)) or ((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_0 = img_V_val_0_V1_status))));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_enable_reg_pp1_iter1, exitcond6_i_i_reg_588, ap_predicate_op80_read_state7, img_V_val_0_V1_status)
    begin
                ap_block_pp1_stage0_subdone <= ((ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (((ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_boolean_1 = ap_predicate_op80_read_state7)) or ((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_0 = img_V_val_0_V1_status))));
    end process;

        ap_block_pp2_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp2_stage0_11001_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364)
    begin
                ap_block_pp2_stage0_11001 <= ((ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1));
    end process;


    ap_block_pp2_stage0_subdone_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, ap_enable_reg_pp2_iter1, eol_2_i_i_reg_364)
    begin
                ap_block_pp2_stage0_subdone <= ((ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state10_pp2_stage0_iter1_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, eol_2_i_i_reg_364)
    begin
                ap_block_state10_pp2_stage0_iter1 <= ((ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out));
    end process;


    ap_block_state1_ignore_call21_assign_proc : process(ap_start, ap_done_reg, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
                ap_block_state1_ignore_call21 <= ((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call22_assign_proc : process(ap_start, ap_done_reg, HwReg_height_cast5_loc_empty_n, HwReg_width_cast6_loc_empty_n, HwReg_height_cast5_loc_out_full_n, HwReg_width_cast6_loc_out_full_n)
    begin
                ap_block_state1_ignore_call22 <= ((ap_const_logic_0 = HwReg_width_cast6_loc_out_full_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_out_full_n) or (ap_const_logic_0 = HwReg_width_cast6_loc_empty_n) or (ap_const_logic_0 = HwReg_height_cast5_loc_empty_n) or (ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_reg_unsigned_short_s_fu_413_ap_done, grp_reg_unsigned_short_s_fu_419_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_const_logic_0 = grp_reg_unsigned_short_s_fu_419_ap_done) or (ap_const_logic_0 = grp_reg_unsigned_short_s_fu_413_ap_done));
    end process;

        ap_block_state6_pp1_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp1_stage0_iter1_assign_proc : process(AXI_video_strm_V_data_V_0_vld_out, exitcond6_i_i_reg_588, ap_predicate_op80_read_state7, img_V_val_0_V1_status)
    begin
                ap_block_state7_pp1_stage0_iter1 <= (((ap_const_logic_0 = AXI_video_strm_V_data_V_0_vld_out) and (ap_const_boolean_1 = ap_predicate_op80_read_state7)) or ((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_0 = img_V_val_0_V1_status)));
    end process;

        ap_block_state9_pp2_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_511_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588)
    begin
                ap_condition_511 <= ((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, exitcond5_i_i_fu_443_p2, ap_CS_fsm_state5)
    begin
        if (((ap_const_lv1_1 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);
    ap_enable_pp2 <= (ap_idle_pp2 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter1, ap_enable_reg_pp1_iter0)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp1_iter0) and (ap_const_logic_0 = ap_enable_reg_pp1_iter1))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp2_assign_proc : process(ap_enable_reg_pp2_iter1, ap_enable_reg_pp2_iter0)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp2_iter0) and (ap_const_logic_0 = ap_enable_reg_pp2_iter1))) then 
            ap_idle_pp2 <= ap_const_logic_1;
        else 
            ap_idle_pp2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4_assign_proc : process(AXI_video_strm_V_last_V_0_data_out, brmerge_i_i_reg_597, eol_reg_317, ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339, ap_condition_511)
    begin
        if ((ap_condition_511 = ap_const_boolean_1)) then
            if ((ap_const_lv1_1 = brmerge_i_i_reg_597)) then 
                ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 <= eol_reg_317;
            elsif ((ap_const_lv1_0 = brmerge_i_i_reg_597)) then 
                ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 <= AXI_video_strm_V_last_V_0_data_out;
            else 
                ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 <= ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339;
            end if;
        else 
            ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 <= ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339;
        end if; 
    end process;


    ap_phi_mux_eol_2_i_i_phi_fu_367_p4_assign_proc : process(AXI_video_strm_V_last_V_0_data_out, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0, eol_2_i_i_reg_364)
    begin
        if (((ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_block_pp2_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0))) then 
            ap_phi_mux_eol_2_i_i_phi_fu_367_p4 <= AXI_video_strm_V_last_V_0_data_out;
        else 
            ap_phi_mux_eol_2_i_i_phi_fu_367_p4 <= eol_2_i_i_reg_364;
        end if; 
    end process;


    ap_phi_mux_eol_i_i_phi_fu_298_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588, eol_i_i_reg_294, ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4)
    begin
        if (((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            ap_phi_mux_eol_i_i_phi_fu_298_p4 <= ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
        else 
            ap_phi_mux_eol_i_i_phi_fu_298_p4 <= eol_i_i_reg_294;
        end if; 
    end process;


    ap_phi_mux_p_Val2_s_phi_fu_356_p4_assign_proc : process(AXI_video_strm_V_data_V_0_data_out, brmerge_i_i_reg_597, axi_data_V_1_i_i_reg_328, ap_phi_reg_pp1_iter1_p_Val2_s_reg_352, ap_condition_511)
    begin
        if ((ap_condition_511 = ap_const_boolean_1)) then
            if ((ap_const_lv1_1 = brmerge_i_i_reg_597)) then 
                ap_phi_mux_p_Val2_s_phi_fu_356_p4 <= axi_data_V_1_i_i_reg_328;
            elsif ((ap_const_lv1_0 = brmerge_i_i_reg_597)) then 
                ap_phi_mux_p_Val2_s_phi_fu_356_p4 <= AXI_video_strm_V_data_V_0_data_out;
            else 
                ap_phi_mux_p_Val2_s_phi_fu_356_p4 <= ap_phi_reg_pp1_iter1_p_Val2_s_reg_352;
            end if;
        else 
            ap_phi_mux_p_Val2_s_phi_fu_356_p4 <= ap_phi_reg_pp1_iter1_p_Val2_s_reg_352;
        end if; 
    end process;

    ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339 <= "X";
    ap_phi_reg_pp1_iter1_p_Val2_s_reg_352 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op80_read_state7_assign_proc : process(exitcond6_i_i_reg_588, brmerge_i_i_reg_597)
    begin
                ap_predicate_op80_read_state7 <= ((ap_const_lv1_0 = brmerge_i_i_reg_597) and (ap_const_lv1_0 = exitcond6_i_i_reg_588));
    end process;


    ap_ready_assign_proc : process(exitcond5_i_i_fu_443_p2, ap_CS_fsm_state5)
    begin
        if (((ap_const_lv1_1 = exitcond5_i_i_fu_443_p2) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_i_i_fu_468_p2 <= (sof_1_i_i_fu_194 or ap_phi_mux_eol_i_i_phi_fu_298_p4);
    exitcond5_i_i_fu_443_p2 <= "1" when (i_cast_i_i_fu_439_p1 = tmp_i_i_reg_542) else "0";
    exitcond6_i_i_fu_454_p2 <= "1" when (j_i_i_reg_306 = tmp_i_i_230_reg_547) else "0";
    grp_reg_unsigned_short_s_fu_413_ap_start <= ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start;
    grp_reg_unsigned_short_s_fu_419_ap_start <= ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start;
    i_cast_i_i_fu_439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_i_i_reg_283),12));
    i_fu_448_p2 <= std_logic_vector(unsigned(i_i_i_reg_283) + unsigned(ap_const_lv11_1));
    img_V_val_0_V1_status <= (img_V_val_2_V_full_n and img_V_val_1_V_full_n and img_V_val_0_V_full_n);

    img_V_val_0_V1_update_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, exitcond6_i_i_reg_588, ap_block_pp1_stage0_11001)
    begin
        if (((ap_block_pp1_stage0_11001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img_V_val_0_V1_update <= ap_const_logic_1;
        else 
            img_V_val_0_V1_update <= ap_const_logic_0;
        end if; 
    end process;


    img_V_val_0_V_blk_n_assign_proc : process(img_V_val_0_V_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588)
    begin
        if (((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img_V_val_0_V_blk_n <= img_V_val_0_V_full_n;
        else 
            img_V_val_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_V_val_0_V_din <= 
        pix_val_0_V_fu_479_p4 when (sel_tmp2_reg_572(0) = '1') else 
        pix_val_1_V_8_fu_489_p1;
    img_V_val_0_V_write <= img_V_val_0_V1_update;

    img_V_val_1_V_blk_n_assign_proc : process(img_V_val_1_V_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588)
    begin
        if (((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img_V_val_1_V_blk_n <= img_V_val_1_V_full_n;
        else 
            img_V_val_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_V_val_1_V_din <= 
        pix_val_1_V_8_fu_489_p1 when (sel_tmp2_reg_572(0) = '1') else 
        pix_val_2_V_fu_493_p4;
    img_V_val_1_V_write <= img_V_val_0_V1_update;

    img_V_val_2_V_blk_n_assign_proc : process(img_V_val_2_V_full_n, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588)
    begin
        if (((ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0))) then 
            img_V_val_2_V_blk_n <= img_V_val_2_V_full_n;
        else 
            img_V_val_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_V_val_2_V_din <= 
        pix_val_2_V_fu_493_p4 when (sel_tmp2_reg_572(0) = '1') else 
        pix_val_0_V_fu_479_p4;
    img_V_val_2_V_write <= img_V_val_0_V1_update;
    j_fu_459_p2 <= std_logic_vector(unsigned(j_i_i_reg_306) + unsigned(ap_const_lv12_1));
    pix_val_0_V_fu_479_p4 <= ap_phi_mux_p_Val2_s_phi_fu_356_p4(23 downto 16);
    pix_val_1_V_8_fu_489_p1 <= ap_phi_mux_p_Val2_s_phi_fu_356_p4(8 - 1 downto 0);
    pix_val_2_V_fu_493_p4 <= ap_phi_mux_p_Val2_s_phi_fu_356_p4(15 downto 8);

    s_axis_video_TDATA_blk_n_assign_proc : process(AXI_video_strm_V_data_V_0_state, ap_CS_fsm_state3, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, ap_block_pp1_stage0, exitcond6_i_i_reg_588, brmerge_i_i_reg_597, ap_CS_fsm_pp2_stage0, ap_enable_reg_pp2_iter1, ap_block_pp2_stage0, eol_2_i_i_reg_364)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_const_lv1_0 = eol_2_i_i_reg_364) and (ap_block_pp2_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp2_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp2_stage0)) or ((ap_const_lv1_0 = brmerge_i_i_reg_597) and (ap_const_lv1_0 = exitcond6_i_i_reg_588) and (ap_block_pp1_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp1_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0)))) then 
            s_axis_video_TDATA_blk_n <= AXI_video_strm_V_data_V_0_state(0);
        else 
            s_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_axis_video_TREADY <= AXI_video_strm_V_dest_V_0_state(1);
    sel_tmp2_fu_429_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    tmp_user_V_fu_425_p1 <= AXI_video_strm_V_user_V_0_data_out;
end behav;
