// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        StrmMPix_V_val_0_V_dout,
        StrmMPix_V_val_0_V_empty_n,
        StrmMPix_V_val_0_V_read,
        StrmMPix_V_val_1_V_dout,
        StrmMPix_V_val_1_V_empty_n,
        StrmMPix_V_val_1_V_read,
        StrmMPix_V_val_2_V_dout,
        StrmMPix_V_val_2_V_empty_n,
        StrmMPix_V_val_2_V_read,
        bytes_plane0_V_V_din,
        bytes_plane0_V_V_full_n,
        bytes_plane0_V_V_write,
        HwReg_height_cast5_loc_dout,
        HwReg_height_cast5_loc_empty_n,
        HwReg_height_cast5_loc_read,
        HwReg_width_cast6_loc_dout,
        HwReg_width_cast6_loc_empty_n,
        HwReg_width_cast6_loc_read,
        tmp_8_loc_dout,
        tmp_8_loc_empty_n,
        tmp_8_loc_read,
        VideoFormat,
        HwReg_height_cast5_loc_out_din,
        HwReg_height_cast5_loc_out_full_n,
        HwReg_height_cast5_loc_out_write,
        tmp_8_loc_out_din,
        tmp_8_loc_out_full_n,
        tmp_8_loc_out_write
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_pp0_stage0 = 13'd16;
parameter    ap_ST_fsm_pp0_stage1 = 13'd32;
parameter    ap_ST_fsm_pp0_stage2 = 13'd64;
parameter    ap_ST_fsm_pp0_stage3 = 13'd128;
parameter    ap_ST_fsm_pp0_stage4 = 13'd256;
parameter    ap_ST_fsm_pp0_stage5 = 13'd512;
parameter    ap_ST_fsm_pp0_stage6 = 13'd1024;
parameter    ap_ST_fsm_pp0_stage7 = 13'd2048;
parameter    ap_ST_fsm_state15 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] StrmMPix_V_val_0_V_dout;
input   StrmMPix_V_val_0_V_empty_n;
output   StrmMPix_V_val_0_V_read;
input  [7:0] StrmMPix_V_val_1_V_dout;
input   StrmMPix_V_val_1_V_empty_n;
output   StrmMPix_V_val_1_V_read;
input  [7:0] StrmMPix_V_val_2_V_dout;
input   StrmMPix_V_val_2_V_empty_n;
output   StrmMPix_V_val_2_V_read;
output  [63:0] bytes_plane0_V_V_din;
input   bytes_plane0_V_V_full_n;
output   bytes_plane0_V_V_write;
input  [10:0] HwReg_height_cast5_loc_dout;
input   HwReg_height_cast5_loc_empty_n;
output   HwReg_height_cast5_loc_read;
input  [11:0] HwReg_width_cast6_loc_dout;
input   HwReg_width_cast6_loc_empty_n;
output   HwReg_width_cast6_loc_read;
input  [15:0] tmp_8_loc_dout;
input   tmp_8_loc_empty_n;
output   tmp_8_loc_read;
input  [7:0] VideoFormat;
output  [10:0] HwReg_height_cast5_loc_out_din;
input   HwReg_height_cast5_loc_out_full_n;
output   HwReg_height_cast5_loc_out_write;
output  [15:0] tmp_8_loc_out_din;
input   tmp_8_loc_out_full_n;
output   tmp_8_loc_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] bytes_plane0_V_V_din;
reg bytes_plane0_V_V_write;
reg HwReg_height_cast5_loc_read;
reg HwReg_width_cast6_loc_read;
reg tmp_8_loc_read;
reg HwReg_height_cast5_loc_out_write;
reg tmp_8_loc_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    StrmMPix_V_val_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage1;
reg   [0:0] tmp_11_i_i_reg_1369;
reg   [0:0] or_cond_i_i_reg_1389;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] or_cond_1_i_i_reg_1420;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
reg   [0:0] or_cond_2_i_i_reg_1454;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4;
reg   [0:0] or_cond_3_i_i_reg_1473;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5;
reg   [0:0] or_cond_4_i_i_reg_1492;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6;
reg   [0:0] or_cond_5_i_i_reg_1511;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7;
reg   [0:0] or_cond_6_i_i_reg_1515;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] or_cond_7_i_i_reg_1519;
reg    StrmMPix_V_val_1_V_blk_n;
reg    StrmMPix_V_val_2_V_blk_n;
reg    bytes_plane0_V_V_blk_n;
reg   [0:0] or_cond1_i_i_reg_1393;
reg   [0:0] or_cond1_1_i_i_reg_1397;
reg   [0:0] or_cond1_2_i_i_reg_1401;
reg   [0:0] ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401;
reg    HwReg_height_cast5_loc_blk_n;
reg    HwReg_width_cast6_loc_blk_n;
reg    tmp_8_loc_blk_n;
reg    HwReg_height_cast5_loc_out_blk_n;
reg    tmp_8_loc_out_blk_n;
reg   [11:0] x_i_i_reg_362;
reg   [7:0] pix_val_V_2_2_i_i_reg_373;
reg   [7:0] pix_val_V_1_2_i_i_reg_383;
reg   [7:0] pix_val_V_0_2_i_i_reg_393;
reg   [7:0] pix_val_V_2_3_i_i_reg_403;
reg   [7:0] pix_val_V_1_3_i_i_reg_414;
reg   [7:0] pix_val_V_0_3_i_i_reg_425;
reg   [7:0] pix_val_V_2_4_i_i_reg_436;
reg   [7:0] pix_val_V_2_5_i_i_reg_469;
reg   [7:0] pix_val_V_1_5_i_i_reg_480;
reg   [7:0] pix_val_V_0_5_i_i_reg_491;
reg   [7:0] pix_val_V_2_6_i_i_reg_502;
reg   [7:0] pix_val_V_1_6_i_i_reg_513;
reg   [7:0] pix_val_V_0_6_i_i_reg_524;
reg   [7:0] pix_val_V_2_7_i_i_reg_535;
reg   [7:0] pix_val_V_1_7_i_i_reg_546;
reg   [10:0] HwReg_height_cast5_l_reg_1215;
reg    ap_block_state1;
wire   [0:0] icmp_fu_656_p2;
reg   [0:0] icmp_reg_1220;
wire   [0:0] tmp_i_i_fu_662_p2;
reg   [0:0] tmp_i_i_reg_1224;
wire   [0:0] icmp1_fu_684_p2;
reg   [0:0] icmp1_reg_1228;
wire   [0:0] tmp_i_i_219_fu_690_p2;
reg   [0:0] tmp_i_i_219_reg_1232;
wire   [0:0] tmp_1_i_i_fu_696_p2;
reg   [0:0] tmp_1_i_i_reg_1236;
wire   [0:0] icmp2_fu_718_p2;
reg   [0:0] icmp2_reg_1240;
wire   [0:0] icmp3_fu_740_p2;
reg   [0:0] icmp3_reg_1244;
wire   [0:0] icmp4_fu_762_p2;
reg   [0:0] icmp4_reg_1248;
reg   [13:0] loopWidth1_cast_i_i_reg_1276;
wire   [2:0] remPix_fu_788_p1;
reg   [2:0] remPix_reg_1281;
reg   [12:0] loopWidth_cast_i_i_reg_1289;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_5_i_i_fu_818_p2;
reg   [0:0] tmp_5_i_i_reg_1295;
wire    ap_CS_fsm_state3;
wire   [16:0] tmp_9_cast_i_i_fu_883_p1;
reg   [16:0] tmp_9_cast_i_i_reg_1300;
wire   [12:0] tmp_10_i_i_fu_886_p2;
reg   [12:0] tmp_10_i_i_reg_1305;
wire   [0:0] tmp_131_i_i_fu_891_p2;
reg   [0:0] tmp_131_i_i_reg_1310;
wire   [0:0] icmp5_fu_907_p2;
reg   [0:0] icmp5_reg_1315;
wire   [0:0] tmp_13_2_i_i_fu_913_p2;
reg   [0:0] tmp_13_2_i_i_reg_1320;
wire   [0:0] icmp6_fu_929_p2;
reg   [0:0] icmp6_reg_1325;
wire   [0:0] tmp_13_4_i_i_fu_935_p2;
reg   [0:0] tmp_13_4_i_i_reg_1330;
wire   [0:0] tmp_13_5_i_i_fu_941_p2;
reg   [0:0] tmp_13_5_i_i_reg_1335;
wire   [0:0] tmp_13_6_i_i_fu_947_p2;
reg   [0:0] tmp_13_6_i_i_reg_1340;
wire   [0:0] tmp_141_i_i_fu_953_p2;
reg   [0:0] tmp_141_i_i_reg_1345;
wire   [0:0] icmp7_fu_969_p2;
reg   [0:0] icmp7_reg_1350;
wire   [0:0] tmp_14_2_i_i_fu_975_p2;
reg   [0:0] tmp_14_2_i_i_reg_1355;
wire   [0:0] exitcond1_i_i_fu_985_p2;
wire    ap_CS_fsm_state4;
wire   [15:0] y_fu_990_p2;
reg   [15:0] y_reg_1364;
wire   [0:0] tmp_11_i_i_fu_1000_p2;
wire    ap_block_state5_pp0_stage0_iter0;
wire    StrmMPix_V_val_0_V0_status;
reg    ap_predicate_op205_read_state13;
reg    ap_block_state13_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] ap_reg_pp0_iter1_tmp_11_i_i_reg_1369;
wire   [11:0] x_fu_1005_p2;
reg   [11:0] x_reg_1373;
wire   [0:0] tmp_12_i_i_fu_1011_p2;
reg   [0:0] tmp_12_i_i_reg_1378;
wire   [0:0] or_cond_i_i_fu_1016_p2;
wire   [0:0] or_cond1_i_i_fu_1021_p2;
wire   [0:0] or_cond1_1_i_i_fu_1026_p2;
wire   [0:0] or_cond1_2_i_i_fu_1031_p2;
reg    ap_predicate_op129_read_state6;
reg    ap_block_state6_pp0_stage1_iter0;
reg    ap_block_state14_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] or_cond_1_i_i_fu_1036_p2;
reg    ap_predicate_op142_read_state7;
reg    ap_block_state7_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
wire   [0:0] or_cond_2_i_i_fu_1049_p2;
reg    ap_predicate_op152_read_state8;
reg    ap_block_state8_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_11001;
wire   [0:0] or_cond_3_i_i_fu_1053_p2;
reg    ap_predicate_op162_read_state9;
reg    ap_block_state9_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_11001;
wire   [0:0] or_cond_4_i_i_fu_1057_p2;
reg    ap_predicate_op172_read_state10;
reg    ap_predicate_op181_write_state10;
reg    ap_block_state10_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_11001;
wire   [0:0] or_cond_5_i_i_fu_1061_p2;
wire   [0:0] or_cond_6_i_i_fu_1065_p2;
wire   [0:0] or_cond_7_i_i_fu_1069_p2;
reg    ap_predicate_op187_read_state11;
reg    ap_block_state11_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_11001;
reg    ap_predicate_op196_read_state12;
reg    ap_block_state12_pp0_stage7_iter0;
reg    ap_block_pp0_stage7_11001;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
reg    ap_block_pp0_stage7_subdone;
reg   [15:0] y_i_i_reg_351;
wire    ap_CS_fsm_state15;
reg   [11:0] ap_phi_mux_x_i_i_phi_fu_366_p4;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_373;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_383;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_393;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_403;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_414;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_425;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_436;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_447;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_458;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_469;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_480;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_491;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_502;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_513;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_524;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_535;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_7_i_i_reg_535;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_546;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_7_i_i_reg_546;
reg   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_557;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_0_7_i_i_reg_557;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_568;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_578;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_588;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588;
reg   [7:0] ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_601_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_2_9_i_i_reg_598;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_598;
reg   [7:0] ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_611_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_1_9_i_i_reg_608;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_608;
reg   [7:0] ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_621_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_val_V_0_9_i_i_reg_618;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_618;
reg    StrmMPix_V_val_0_V0_update;
wire   [63:0] tmp_V_fu_1073_p9;
reg    ap_block_pp0_stage5_01001;
wire   [63:0] tmp_V_1_fu_1094_p9;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] tmp_V_2_fu_1167_p9;
reg    ap_block_pp0_stage1_01001;
reg   [7:0] tmp_val_0_V_fu_282;
reg   [7:0] tmp_val_1_V_fu_286;
reg   [7:0] tmp_val_2_V_fu_290;
wire   [7:0] VideoFormat_off_i_i_fu_640_p2;
wire   [6:0] tmp_fu_646_p4;
wire   [7:0] VideoFormat_off1_i_i_fu_668_p2;
wire   [6:0] tmp_3_fu_674_p4;
wire   [7:0] VideoFormat_off2_i_i_fu_702_p2;
wire   [6:0] tmp_4_fu_708_p4;
wire   [7:0] VideoFormat_off3_i_i_fu_724_p2;
wire   [6:0] tmp_5_fu_730_p4;
wire   [7:0] VideoFormat_off4_i_i_fu_746_p2;
wire   [6:0] tmp_6_fu_752_p4;
wire   [16:0] tmp_2_cast_i_i_fu_768_p1;
wire   [16:0] tmp_3_i_i_fu_772_p2;
wire   [13:0] tmp_4_i_i_fu_797_p2;
wire   [29:0] mul_fu_1208_p2;
wire   [3:0] remPix_cast_i_i_fu_815_p1;
wire   [7:0] p_shl_i_i_fu_831_p3;
wire   [5:0] p_shl1_i_i_fu_842_p3;
wire   [8:0] p_shl_cast_i_i_fu_838_p1;
wire   [8:0] p_shl1_cast_i_i_fu_849_p1;
wire   [8:0] tmp_6_i_i_fu_853_p2;
wire   [8:0] tmp_7_i_i_fu_859_p2;
wire   [2:0] tmp_8_cast_i_i_fu_865_p4;
wire   [3:0] remPix_2_fu_823_p3;
wire   [2:0] tmp_8_fu_897_p4;
wire   [1:0] tmp_9_fu_919_p4;
wire   [2:0] remainTrx_fu_875_p3;
wire   [1:0] tmp_10_fu_959_p4;
wire   [16:0] y_cast_i_i_fu_981_p1;
wire   [12:0] x_cast_i_i_fu_996_p1;
wire   [15:0] mul_fu_1208_p0;
wire   [13:0] mul_fu_1208_p1;
reg   [12:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [29:0] mul_fu_1208_p10;
reg    ap_condition_1214;
reg    ap_condition_1217;
reg    ap_condition_1221;
reg    ap_condition_1224;
reg    ap_condition_1228;
reg    ap_condition_1231;
reg    ap_condition_1235;
reg    ap_condition_1238;
reg    ap_condition_1242;
reg    ap_condition_1246;
reg    ap_condition_553;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 13'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

design_1_v_frmbuf_wr_0_0_v_frmbuf_wr_mul_meOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
v_frmbuf_wr_mul_meOg_U32(
    .din0(mul_fu_1208_p0),
    .din1(mul_fu_1208_p1),
    .dout(mul_fu_1208_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & ((1'd1 == exitcond1_i_i_fu_985_p2) | (1'd1 == icmp3_reg_1244) | (1'd1 == icmp2_reg_1240) | (1'd1 == tmp_1_i_i_reg_1236) | (1'd1 == tmp_i_i_219_reg_1232) | (1'd1 == icmp1_reg_1228) | (1'd1 == tmp_i_i_reg_1224) | (1'd1 == icmp_reg_1220) | (1'd0 == icmp4_reg_1248)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((ap_block_pp0_stage2_subdone == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == icmp4_reg_1248) & (1'd0 == exitcond1_i_i_fu_985_p2) & (1'd0 == icmp3_reg_1244) & (1'd0 == icmp2_reg_1240) & (1'd0 == tmp_1_i_i_reg_1236) & (1'd0 == tmp_i_i_219_reg_1232) & (1'd0 == icmp1_reg_1228) & (tmp_i_i_reg_1224 == 1'd0) & (icmp_reg_1220 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state7) & (((ap_block_pp0_stage2_subdone == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_block_pp0_stage7_subdone == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage7))))) begin
            ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state7 ^ 1'b1);
        end else if ((((ap_block_pp0_stage2_subdone == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_block_pp0_stage7_subdone == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == icmp4_reg_1248) & (1'd0 == exitcond1_i_i_fu_985_p2) & (1'd0 == icmp3_reg_1244) & (1'd0 == icmp2_reg_1240) & (1'd0 == tmp_1_i_i_reg_1236) & (1'd0 == tmp_i_i_219_reg_1232) & (1'd0 == icmp1_reg_1228) & (tmp_i_i_reg_1224 == 1'd0) & (icmp_reg_1220 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1217 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_393 <= tmp_val_0_V_fu_282;
        end else if ((ap_condition_1214 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_393 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1224 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_425 <= ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_393;
        end else if ((ap_condition_1221 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_425 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1231 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_458 <= ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_425;
        end else if ((ap_condition_1228 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_458 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1238 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_491 <= ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_458;
        end else if ((ap_condition_1235 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_491 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1246 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_524 <= ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_491;
        end else if ((ap_condition_1242 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_524 <= StrmMPix_V_val_0_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1217 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_383 <= tmp_val_1_V_fu_286;
        end else if ((ap_condition_1214 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_383 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1224 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_414 <= ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_383;
        end else if ((ap_condition_1221 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_414 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1231 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_447 <= ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_414;
        end else if ((ap_condition_1228 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_447 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1238 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_480 <= ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_447;
        end else if ((ap_condition_1235 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_480 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1246 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_513 <= ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_480;
        end else if ((ap_condition_1242 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_513 <= StrmMPix_V_val_1_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1217 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_373 <= tmp_val_2_V_fu_290;
        end else if ((ap_condition_1214 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_373 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1224 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_403 <= ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_373;
        end else if ((ap_condition_1221 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_403 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1231 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_436 <= ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_403;
        end else if ((ap_condition_1228 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_436 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1238 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_469 <= ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_436;
        end else if ((ap_condition_1235 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_469 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
        if ((ap_condition_1246 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_502 <= ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_469;
        end else if ((ap_condition_1242 == 1'b1)) begin
            ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_502 <= StrmMPix_V_val_2_V_dout;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_553 == 1'b1)) begin
        if (((tmp_11_i_i_reg_1369 == 1'd1) & (or_cond_5_i_i_reg_1511 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_0_7_i_i_reg_557 <= ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_524;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_0_7_i_i_reg_557 <= ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_557;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond_6_i_i_reg_1515 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588 <= ap_phi_reg_pp0_iter1_pix_val_V_0_7_i_i_reg_557;
    end else if (((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588 <= StrmMPix_V_val_0_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588 <= ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_588;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_618 <= StrmMPix_V_val_0_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_618 <= ap_phi_reg_pp0_iter0_pix_val_V_0_9_i_i_reg_618;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_553 == 1'b1)) begin
        if (((tmp_11_i_i_reg_1369 == 1'd1) & (or_cond_5_i_i_reg_1511 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_1_7_i_i_reg_546 <= ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_513;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_1_7_i_i_reg_546 <= ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_546;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond_6_i_i_reg_1515 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578 <= ap_phi_reg_pp0_iter1_pix_val_V_1_7_i_i_reg_546;
    end else if (((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578 <= StrmMPix_V_val_1_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578 <= ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_578;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_608 <= StrmMPix_V_val_1_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_608 <= ap_phi_reg_pp0_iter0_pix_val_V_1_9_i_i_reg_608;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_condition_553 == 1'b1)) begin
        if (((tmp_11_i_i_reg_1369 == 1'd1) & (or_cond_5_i_i_reg_1511 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_pix_val_V_2_7_i_i_reg_535 <= ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_502;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_pix_val_V_2_7_i_i_reg_535 <= ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_535;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond_6_i_i_reg_1515 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568 <= ap_phi_reg_pp0_iter1_pix_val_V_2_7_i_i_reg_535;
    end else if (((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568 <= StrmMPix_V_val_2_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568 <= ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_568;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_598 <= StrmMPix_V_val_2_V_dout;
    end else if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_598 <= ap_phi_reg_pp0_iter0_pix_val_V_2_9_i_i_reg_598;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_i_i_reg_362 <= x_reg_1373;
    end else if (((1'd1 == icmp4_reg_1248) & (1'd0 == exitcond1_i_i_fu_985_p2) & (1'd0 == icmp3_reg_1244) & (1'd0 == icmp2_reg_1240) & (1'd0 == tmp_1_i_i_reg_1236) & (1'd0 == tmp_i_i_219_reg_1232) & (1'd0 == icmp1_reg_1228) & (tmp_i_i_reg_1224 == 1'd0) & (icmp_reg_1220 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        x_i_i_reg_362 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        y_i_i_reg_351 <= y_reg_1364;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        y_i_i_reg_351 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_l_reg_1215 <= HwReg_height_cast5_loc_dout;
        icmp_reg_1220 <= icmp_fu_656_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == or_cond_5_i_i_reg_1511) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage6_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_phi_reg_pp0_iter0_pix_val_V_0_7_i_i_reg_557 <= StrmMPix_V_val_0_V_dout;
        ap_phi_reg_pp0_iter0_pix_val_V_1_7_i_i_reg_546 <= StrmMPix_V_val_1_V_dout;
        ap_phi_reg_pp0_iter0_pix_val_V_2_7_i_i_reg_535 <= StrmMPix_V_val_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401 <= or_cond1_2_i_i_reg_1401;
        ap_reg_pp0_iter1_tmp_11_i_i_reg_1369 <= tmp_11_i_i_reg_1369;
        tmp_11_i_i_reg_1369 <= tmp_11_i_i_fu_1000_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp1_reg_1228 <= icmp1_fu_684_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd0 == tmp_1_i_i_fu_696_p2) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp2_reg_1240 <= icmp2_fu_718_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd0 == icmp2_fu_718_p2) & (1'd0 == tmp_1_i_i_fu_696_p2) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp3_reg_1244 <= icmp3_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd0 == icmp3_fu_740_p2) & (1'd0 == icmp2_fu_718_p2) & (1'd0 == tmp_1_i_i_fu_696_p2) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp4_reg_1248 <= icmp4_fu_762_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp5_reg_1315 <= icmp5_fu_907_p2;
        icmp6_reg_1325 <= icmp6_fu_929_p2;
        icmp7_reg_1350 <= icmp7_fu_969_p2;
        tmp_10_i_i_reg_1305 <= tmp_10_i_i_fu_886_p2;
        tmp_131_i_i_reg_1310 <= tmp_131_i_i_fu_891_p2;
        tmp_13_2_i_i_reg_1320 <= tmp_13_2_i_i_fu_913_p2;
        tmp_13_4_i_i_reg_1330 <= tmp_13_4_i_i_fu_935_p2;
        tmp_13_5_i_i_reg_1335 <= tmp_13_5_i_i_fu_941_p2;
        tmp_13_6_i_i_reg_1340 <= tmp_13_6_i_i_fu_947_p2;
        tmp_141_i_i_reg_1345 <= tmp_141_i_i_fu_953_p2;
        tmp_14_2_i_i_reg_1355 <= tmp_14_2_i_i_fu_975_p2;
        tmp_5_i_i_reg_1295 <= tmp_5_i_i_fu_818_p2;
        tmp_9_cast_i_i_reg_1300[10 : 0] <= tmp_9_cast_i_i_fu_883_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd1 == icmp4_fu_762_p2) & (1'd0 == icmp3_fu_740_p2) & (1'd0 == icmp2_fu_718_p2) & (1'd0 == tmp_1_i_i_fu_696_p2) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        loopWidth1_cast_i_i_reg_1276 <= {{tmp_3_i_i_fu_772_p2[16:3]}};
        remPix_reg_1281 <= remPix_fu_788_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        loopWidth_cast_i_i_reg_1289 <= {{mul_fu_1208_p2[28:16]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == tmp_11_i_i_fu_1000_p2) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_cond1_1_i_i_reg_1397 <= or_cond1_1_i_i_fu_1026_p2;
        or_cond1_2_i_i_reg_1401 <= or_cond1_2_i_i_fu_1031_p2;
        or_cond1_i_i_reg_1393 <= or_cond1_i_i_fu_1021_p2;
        or_cond_i_i_reg_1389 <= or_cond_i_i_fu_1016_p2;
        tmp_12_i_i_reg_1378 <= tmp_12_i_i_fu_1011_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage1_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_cond_1_i_i_reg_1420 <= or_cond_1_i_i_fu_1036_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage2_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        or_cond_2_i_i_reg_1454 <= or_cond_2_i_i_fu_1049_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage3_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        or_cond_3_i_i_reg_1473 <= or_cond_3_i_i_fu_1053_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage4_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        or_cond_4_i_i_reg_1492 <= or_cond_4_i_i_fu_1057_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        or_cond_5_i_i_reg_1511 <= or_cond_5_i_i_fu_1061_p2;
        or_cond_6_i_i_reg_1515 <= or_cond_6_i_i_fu_1065_p2;
        or_cond_7_i_i_reg_1519 <= or_cond_7_i_i_fu_1069_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage3_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        pix_val_V_0_2_i_i_reg_393 <= ap_phi_reg_pp0_iter0_pix_val_V_0_2_i_i_reg_393;
        pix_val_V_1_2_i_i_reg_383 <= ap_phi_reg_pp0_iter0_pix_val_V_1_2_i_i_reg_383;
        pix_val_V_2_2_i_i_reg_373 <= ap_phi_reg_pp0_iter0_pix_val_V_2_2_i_i_reg_373;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage4_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        pix_val_V_0_3_i_i_reg_425 <= ap_phi_reg_pp0_iter0_pix_val_V_0_3_i_i_reg_425;
        pix_val_V_1_3_i_i_reg_414 <= ap_phi_reg_pp0_iter0_pix_val_V_1_3_i_i_reg_414;
        pix_val_V_2_3_i_i_reg_403 <= ap_phi_reg_pp0_iter0_pix_val_V_2_3_i_i_reg_403;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage6_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        pix_val_V_0_5_i_i_reg_491 <= ap_phi_reg_pp0_iter0_pix_val_V_0_5_i_i_reg_491;
        pix_val_V_1_5_i_i_reg_480 <= ap_phi_reg_pp0_iter0_pix_val_V_1_5_i_i_reg_480;
        pix_val_V_2_5_i_i_reg_469 <= ap_phi_reg_pp0_iter0_pix_val_V_2_5_i_i_reg_469;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        pix_val_V_0_6_i_i_reg_524 <= ap_phi_reg_pp0_iter0_pix_val_V_0_6_i_i_reg_524;
        pix_val_V_1_6_i_i_reg_513 <= ap_phi_reg_pp0_iter0_pix_val_V_1_6_i_i_reg_513;
        pix_val_V_2_6_i_i_reg_502 <= ap_phi_reg_pp0_iter0_pix_val_V_2_6_i_i_reg_502;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_val_V_1_7_i_i_reg_546 <= ap_phi_reg_pp0_iter1_pix_val_V_1_7_i_i_reg_546;
        pix_val_V_2_7_i_i_reg_535 <= ap_phi_reg_pp0_iter1_pix_val_V_2_7_i_i_reg_535;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        pix_val_V_2_4_i_i_reg_436 <= ap_phi_reg_pp0_iter0_pix_val_V_2_4_i_i_reg_436;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_1_i_i_reg_1236 <= tmp_1_i_i_fu_696_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_i_i_219_reg_1232 <= tmp_i_i_219_fu_690_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_i_i_reg_1224 <= tmp_i_i_fu_662_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_reg_pp0_iter1_tmp_11_i_i_reg_1369) & (ap_block_pp0_stage1_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        tmp_val_0_V_fu_282 <= ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_621_p4;
        tmp_val_1_V_fu_286 <= ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_611_p4;
        tmp_val_2_V_fu_290 <= ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_601_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_reg_1373 <= x_fu_1005_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == icmp4_reg_1248) & (1'd0 == icmp3_reg_1244) & (1'd0 == icmp2_reg_1240) & (1'd0 == tmp_1_i_i_reg_1236) & (1'd0 == tmp_i_i_219_reg_1232) & (1'd0 == icmp1_reg_1228) & (tmp_i_i_reg_1224 == 1'd0) & (icmp_reg_1220 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        y_reg_1364 <= y_fu_990_p2;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_blk_n = HwReg_height_cast5_loc_empty_n;
    end else begin
        HwReg_height_cast5_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_blk_n = HwReg_height_cast5_loc_out_full_n;
    end else begin
        HwReg_height_cast5_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_write = 1'b1;
    end else begin
        HwReg_height_cast5_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_read = 1'b1;
    end else begin
        HwReg_height_cast5_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_blk_n = HwReg_width_cast6_loc_empty_n;
    end else begin
        HwReg_width_cast6_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_read = 1'b1;
    end else begin
        HwReg_width_cast6_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage2_11001 == 1'b0) & (1'b1 == ap_predicate_op142_read_state7) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_predicate_op196_read_state12) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_block_pp0_stage6_11001 == 1'b0) & (1'b1 == ap_predicate_op187_read_state11) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_predicate_op172_read_state10) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_block_pp0_stage4_11001 == 1'b0) & (1'b1 == ap_predicate_op162_read_state9) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_block_pp0_stage3_11001 == 1'b0) & (1'b1 == ap_predicate_op152_read_state8) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((ap_block_pp0_stage1_11001 == 1'b0) & (1'b1 == ap_predicate_op129_read_state6) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_predicate_op205_read_state13) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        StrmMPix_V_val_0_V0_update = 1'b1;
    end else begin
        StrmMPix_V_val_0_V0_update = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0)) | ((ap_block_pp0_stage2 == 1'b0) & (1'd1 == or_cond_1_i_i_reg_1420) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7 == 1'b0)) | ((1'd1 == or_cond_5_i_i_reg_1511) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6 == 1'b0)) | ((1'd1 == or_cond_4_i_i_reg_1492) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5 == 1'b0)) | ((1'd1 == or_cond_3_i_i_reg_1473) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_block_pp0_stage4 == 1'b0)) | ((1'd1 == or_cond_2_i_i_reg_1454) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3 == 1'b0)) | ((1'd1 == or_cond_i_i_reg_1389) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_0_V_blk_n = StrmMPix_V_val_0_V_empty_n;
    end else begin
        StrmMPix_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0)) | ((ap_block_pp0_stage2 == 1'b0) & (1'd1 == or_cond_1_i_i_reg_1420) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7 == 1'b0)) | ((1'd1 == or_cond_5_i_i_reg_1511) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6 == 1'b0)) | ((1'd1 == or_cond_4_i_i_reg_1492) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5 == 1'b0)) | ((1'd1 == or_cond_3_i_i_reg_1473) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_block_pp0_stage4 == 1'b0)) | ((1'd1 == or_cond_2_i_i_reg_1454) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3 == 1'b0)) | ((1'd1 == or_cond_i_i_reg_1389) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_1_V_blk_n = StrmMPix_V_val_1_V_empty_n;
    end else begin
        StrmMPix_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0)) | ((ap_block_pp0_stage2 == 1'b0) & (1'd1 == or_cond_1_i_i_reg_1420) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7 == 1'b0)) | ((1'd1 == or_cond_5_i_i_reg_1511) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6 == 1'b0)) | ((1'd1 == or_cond_4_i_i_reg_1492) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5 == 1'b0)) | ((1'd1 == or_cond_3_i_i_reg_1473) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_block_pp0_stage4 == 1'b0)) | ((1'd1 == or_cond_2_i_i_reg_1454) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3 == 1'b0)) | ((1'd1 == or_cond_i_i_reg_1389) & (tmp_11_i_i_reg_1369 == 1'd1) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        StrmMPix_V_val_2_V_blk_n = StrmMPix_V_val_2_V_empty_n;
    end else begin
        StrmMPix_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((tmp_11_i_i_reg_1369 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((1'd1 == exitcond1_i_i_fu_985_p2) | (1'd1 == icmp3_reg_1244) | (1'd1 == icmp2_reg_1240) | (1'd1 == tmp_1_i_i_reg_1236) | (1'd1 == tmp_i_i_219_reg_1232) | (1'd1 == icmp1_reg_1228) | (1'd1 == tmp_i_i_reg_1224) | (1'd1 == icmp_reg_1220) | (1'd0 == icmp4_reg_1248)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == ap_reg_pp0_iter1_tmp_11_i_i_reg_1369) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1) & (or_cond_7_i_i_reg_1519 == 1'd0))) begin
        ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_621_p4 = ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588;
    end else begin
        ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_621_p4 = ap_phi_reg_pp0_iter1_pix_val_V_0_9_i_i_reg_618;
    end
end

always @ (*) begin
    if (((1'd1 == ap_reg_pp0_iter1_tmp_11_i_i_reg_1369) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1) & (or_cond_7_i_i_reg_1519 == 1'd0))) begin
        ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_611_p4 = ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578;
    end else begin
        ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_611_p4 = ap_phi_reg_pp0_iter1_pix_val_V_1_9_i_i_reg_608;
    end
end

always @ (*) begin
    if (((1'd1 == ap_reg_pp0_iter1_tmp_11_i_i_reg_1369) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1) & (or_cond_7_i_i_reg_1519 == 1'd0))) begin
        ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_601_p4 = ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568;
    end else begin
        ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_601_p4 = ap_phi_reg_pp0_iter1_pix_val_V_2_9_i_i_reg_598;
    end
end

always @ (*) begin
    if (((tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0))) begin
        ap_phi_mux_x_i_i_phi_fu_366_p4 = x_reg_1373;
    end else begin
        ap_phi_mux_x_i_i_phi_fu_366_p4 = x_i_i_reg_362;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & ((1'd1 == exitcond1_i_i_fu_985_p2) | (1'd1 == icmp3_reg_1244) | (1'd1 == icmp2_reg_1240) | (1'd1 == tmp_1_i_i_reg_1236) | (1'd1 == tmp_i_i_219_reg_1232) | (1'd1 == icmp1_reg_1228) | (1'd1 == tmp_i_i_reg_1224) | (1'd1 == icmp_reg_1220) | (1'd0 == icmp4_reg_1248)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'd1 == or_cond1_i_i_reg_1393) & (tmp_11_i_i_reg_1369 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5 == 1'b0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (ap_block_pp0_stage1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0 == 1'b0)))) begin
        bytes_plane0_V_V_blk_n = bytes_plane0_V_V_full_n;
    end else begin
        bytes_plane0_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (ap_block_pp0_stage1_01001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        bytes_plane0_V_V_din = tmp_V_2_fu_1167_p9;
    end else if (((1'd1 == or_cond1_1_i_i_reg_1397) & (ap_block_pp0_stage0_01001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bytes_plane0_V_V_din = tmp_V_1_fu_1094_p9;
    end else if (((ap_block_pp0_stage5_01001 == 1'b0) & (1'b1 == ap_predicate_op181_write_state10) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        bytes_plane0_V_V_din = tmp_V_fu_1073_p9;
    end else begin
        bytes_plane0_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_predicate_op181_write_state10) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (ap_block_pp0_stage1_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter1)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (ap_block_pp0_stage0_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        bytes_plane0_V_V_write = 1'b1;
    end else begin
        bytes_plane0_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_8_loc_blk_n = tmp_8_loc_empty_n;
    end else begin
        tmp_8_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_8_loc_out_blk_n = tmp_8_loc_out_full_n;
    end else begin
        tmp_8_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_8_loc_out_write = 1'b1;
    end else begin
        tmp_8_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_8_loc_read = 1'b1;
    end else begin
        tmp_8_loc_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'd1 == icmp4_fu_762_p2) & (1'd0 == icmp3_fu_740_p2) & (1'd0 == icmp2_fu_718_p2) & (1'd0 == tmp_1_i_i_fu_696_p2) & (1'd0 == tmp_i_i_219_fu_690_p2) & (1'd0 == icmp1_fu_684_p2) & (tmp_i_i_fu_662_p2 == 1'd0) & (icmp_fu_656_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1) & ((1'd1 == icmp3_fu_740_p2) | (1'd1 == icmp2_fu_718_p2) | (1'd1 == tmp_1_i_i_fu_696_p2) | (1'd1 == tmp_i_i_219_fu_690_p2) | (1'd1 == icmp1_fu_684_p2) | (1'd1 == tmp_i_i_fu_662_p2) | (1'd1 == icmp_fu_656_p2) | (1'd0 == icmp4_fu_762_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & ((1'd1 == exitcond1_i_i_fu_985_p2) | (1'd1 == icmp3_reg_1244) | (1'd1 == icmp2_reg_1240) | (1'd1 == tmp_1_i_i_reg_1236) | (1'd1 == tmp_i_i_219_reg_1232) | (1'd1 == icmp1_reg_1228) | (1'd1 == tmp_i_i_reg_1224) | (1'd1 == icmp_reg_1220) | (1'd0 == icmp4_reg_1248)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_block_pp0_stage0_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((ap_block_pp0_stage1_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((~((tmp_11_i_i_reg_1369 == 1'd0) & (ap_block_pp0_stage2_subdone == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0)) & (ap_block_pp0_stage2_subdone == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((tmp_11_i_i_reg_1369 == 1'd0) & (ap_block_pp0_stage2_subdone == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((ap_block_pp0_stage3_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((ap_block_pp0_stage4_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((ap_block_pp0_stage5_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((ap_block_pp0_stage6_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((ap_block_pp0_stage7_subdone == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_height_cast5_loc_out_din = HwReg_height_cast5_loc_dout;

assign StrmMPix_V_val_0_V0_status = (StrmMPix_V_val_2_V_empty_n & StrmMPix_V_val_1_V_empty_n & StrmMPix_V_val_0_V_empty_n);

assign StrmMPix_V_val_0_V_read = StrmMPix_V_val_0_V0_update;

assign StrmMPix_V_val_1_V_read = StrmMPix_V_val_0_V0_update;

assign StrmMPix_V_val_2_V_read = StrmMPix_V_val_0_V0_update;

assign VideoFormat_off1_i_i_fu_668_p2 = ($signed(VideoFormat) + $signed(8'd241));

assign VideoFormat_off2_i_i_fu_702_p2 = ($signed(VideoFormat) + $signed(8'd238));

assign VideoFormat_off3_i_i_fu_724_p2 = ($signed(VideoFormat) + $signed(8'd234));

assign VideoFormat_off4_i_i_fu_746_p2 = ($signed(VideoFormat) + $signed(8'd236));

assign VideoFormat_off_i_i_fu_640_p2 = ($signed(VideoFormat) + $signed(8'd246));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b1 == ap_predicate_op205_read_state13) & (1'b0 == StrmMPix_V_val_0_V0_status)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (1'b0 == bytes_plane0_V_V_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b1 == ap_predicate_op205_read_state13) & (1'b0 == StrmMPix_V_val_0_V0_status)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (1'b0 == bytes_plane0_V_V_full_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b1 == ap_enable_reg_pp0_iter1) & (((1'b1 == ap_predicate_op205_read_state13) & (1'b0 == StrmMPix_V_val_0_V0_status)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (1'b0 == bytes_plane0_V_V_full_n))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((1'b1 == ap_predicate_op129_read_state6) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (1'b0 == bytes_plane0_V_V_full_n) & (1'b1 == ap_enable_reg_pp0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((1'b1 == ap_predicate_op129_read_state6) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (1'b0 == bytes_plane0_V_V_full_n) & (1'b1 == ap_enable_reg_pp0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((1'b1 == ap_predicate_op129_read_state6) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (1'b0 == bytes_plane0_V_V_full_n) & (1'b1 == ap_enable_reg_pp0_iter1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((1'b1 == ap_predicate_op142_read_state7) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b1 == ap_predicate_op142_read_state7) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((1'b1 == ap_predicate_op152_read_state8) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'b1 == ap_predicate_op152_read_state8) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((1'b1 == ap_predicate_op162_read_state9) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((1'b1 == ap_predicate_op162_read_state9) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_01001 = ((1'b1 == ap_enable_reg_pp0_iter0) & (((1'b1 == ap_predicate_op181_write_state10) & (1'b0 == bytes_plane0_V_V_full_n)) | ((1'b1 == ap_predicate_op172_read_state10) & (1'b0 == StrmMPix_V_val_0_V0_status))));
end

always @ (*) begin
    ap_block_pp0_stage5_11001 = ((1'b1 == ap_enable_reg_pp0_iter0) & (((1'b1 == ap_predicate_op181_write_state10) & (1'b0 == bytes_plane0_V_V_full_n)) | ((1'b1 == ap_predicate_op172_read_state10) & (1'b0 == StrmMPix_V_val_0_V0_status))));
end

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((1'b1 == ap_enable_reg_pp0_iter0) & (((1'b1 == ap_predicate_op181_write_state10) & (1'b0 == bytes_plane0_V_V_full_n)) | ((1'b1 == ap_predicate_op172_read_state10) & (1'b0 == StrmMPix_V_val_0_V0_status))));
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001 = ((1'b1 == ap_predicate_op187_read_state11) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((1'b1 == ap_predicate_op187_read_state11) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001 = ((1'b1 == ap_predicate_op196_read_state12) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((1'b1 == ap_predicate_op196_read_state12) & (1'b0 == StrmMPix_V_val_0_V0_status) & (1'b1 == ap_enable_reg_pp0_iter0));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == tmp_8_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == tmp_8_loc_empty_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp0_stage5_iter0 = (((1'b1 == ap_predicate_op181_write_state10) & (1'b0 == bytes_plane0_V_V_full_n)) | ((1'b1 == ap_predicate_op172_read_state10) & (1'b0 == StrmMPix_V_val_0_V0_status)));
end

always @ (*) begin
    ap_block_state11_pp0_stage6_iter0 = ((1'b1 == ap_predicate_op187_read_state11) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state12_pp0_stage7_iter0 = ((1'b1 == ap_predicate_op196_read_state12) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter1 = (((1'b1 == ap_predicate_op205_read_state13) & (1'b0 == StrmMPix_V_val_0_V0_status)) | ((1'd1 == or_cond1_1_i_i_reg_1397) & (1'b0 == bytes_plane0_V_V_full_n)));
end

always @ (*) begin
    ap_block_state14_pp0_stage1_iter1 = ((1'd1 == ap_reg_pp0_iter1_or_cond1_2_i_i_reg_1401) & (1'b0 == bytes_plane0_V_V_full_n));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage1_iter0 = ((1'b1 == ap_predicate_op129_read_state6) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state7_pp0_stage2_iter0 = ((1'b1 == ap_predicate_op142_read_state7) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state8_pp0_stage3_iter0 = ((1'b1 == ap_predicate_op152_read_state8) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_block_state9_pp0_stage4_iter0 = ((1'b1 == ap_predicate_op162_read_state9) & (1'b0 == StrmMPix_V_val_0_V0_status));
end

always @ (*) begin
    ap_condition_1214 = ((1'd1 == or_cond_i_i_reg_1389) & (ap_block_pp0_stage1_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_1217 = ((or_cond_i_i_reg_1389 == 1'd0) & (ap_block_pp0_stage2_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_1221 = ((1'd1 == or_cond_1_i_i_reg_1420) & (ap_block_pp0_stage2_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_condition_1224 = ((ap_block_pp0_stage3_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (or_cond_1_i_i_reg_1420 == 1'd0));
end

always @ (*) begin
    ap_condition_1228 = ((1'd1 == or_cond_2_i_i_reg_1454) & (ap_block_pp0_stage3_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

always @ (*) begin
    ap_condition_1231 = ((ap_block_pp0_stage4_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (or_cond_2_i_i_reg_1454 == 1'd0));
end

always @ (*) begin
    ap_condition_1235 = ((1'd1 == or_cond_3_i_i_reg_1473) & (ap_block_pp0_stage4_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage4));
end

always @ (*) begin
    ap_condition_1238 = ((ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (or_cond_3_i_i_reg_1473 == 1'd0));
end

always @ (*) begin
    ap_condition_1242 = ((1'd1 == or_cond_4_i_i_reg_1492) & (ap_block_pp0_stage5_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage5));
end

always @ (*) begin
    ap_condition_1246 = ((ap_block_pp0_stage6_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (or_cond_4_i_i_reg_1492 == 1'd0));
end

always @ (*) begin
    ap_condition_553 = ((ap_block_pp0_stage7_11001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_pix_val_V_0_8_i_i_reg_588 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_0_9_i_i_reg_618 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_1_8_i_i_reg_578 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_1_9_i_i_reg_608 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_2_8_i_i_reg_568 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_val_V_2_9_i_i_reg_598 = 'bx;

always @ (*) begin
    ap_predicate_op129_read_state6 = ((1'd1 == or_cond_i_i_reg_1389) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op142_read_state7 = ((1'd1 == or_cond_1_i_i_reg_1420) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op152_read_state8 = ((1'd1 == or_cond_2_i_i_reg_1454) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op162_read_state9 = ((1'd1 == or_cond_3_i_i_reg_1473) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op172_read_state10 = ((1'd1 == or_cond_4_i_i_reg_1492) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op181_write_state10 = ((1'd1 == or_cond1_i_i_reg_1393) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op187_read_state11 = ((1'd1 == or_cond_5_i_i_reg_1511) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op196_read_state12 = ((1'd1 == or_cond_6_i_i_reg_1515) & (tmp_11_i_i_reg_1369 == 1'd1));
end

always @ (*) begin
    ap_predicate_op205_read_state13 = ((1'd1 == or_cond_7_i_i_reg_1519) & (tmp_11_i_i_reg_1369 == 1'd1));
end

assign exitcond1_i_i_fu_985_p2 = ((y_cast_i_i_fu_981_p1 == tmp_9_cast_i_i_reg_1300) ? 1'b1 : 1'b0);

assign icmp1_fu_684_p2 = ((tmp_3_fu_674_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_718_p2 = ((tmp_4_fu_708_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp3_fu_740_p2 = ((tmp_5_fu_730_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_762_p2 = ((tmp_6_fu_752_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp5_fu_907_p2 = ((tmp_8_fu_897_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp6_fu_929_p2 = ((tmp_9_fu_919_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_969_p2 = ((tmp_10_fu_959_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_656_p2 = ((tmp_fu_646_p4 == 7'd0) ? 1'b1 : 1'b0);

assign mul_fu_1208_p0 = 30'd21846;

assign mul_fu_1208_p1 = mul_fu_1208_p10;

assign mul_fu_1208_p10 = tmp_4_i_i_fu_797_p2;

assign or_cond1_1_i_i_fu_1026_p2 = (tmp_12_i_i_fu_1011_p2 | icmp7_reg_1350);

assign or_cond1_2_i_i_fu_1031_p2 = (tmp_14_2_i_i_reg_1355 | tmp_12_i_i_fu_1011_p2);

assign or_cond1_i_i_fu_1021_p2 = (tmp_141_i_i_reg_1345 | tmp_12_i_i_fu_1011_p2);

assign or_cond_1_i_i_fu_1036_p2 = (tmp_12_i_i_reg_1378 | icmp5_reg_1315);

assign or_cond_2_i_i_fu_1049_p2 = (tmp_13_2_i_i_reg_1320 | tmp_12_i_i_reg_1378);

assign or_cond_3_i_i_fu_1053_p2 = (tmp_12_i_i_reg_1378 | icmp6_reg_1325);

assign or_cond_4_i_i_fu_1057_p2 = (tmp_13_4_i_i_reg_1330 | tmp_12_i_i_reg_1378);

assign or_cond_5_i_i_fu_1061_p2 = (tmp_13_5_i_i_reg_1335 | tmp_12_i_i_reg_1378);

assign or_cond_6_i_i_fu_1065_p2 = (tmp_13_6_i_i_reg_1340 | tmp_12_i_i_reg_1378);

assign or_cond_7_i_i_fu_1069_p2 = (tmp_5_i_i_reg_1295 | tmp_12_i_i_reg_1378);

assign or_cond_i_i_fu_1016_p2 = (tmp_131_i_i_reg_1310 | tmp_12_i_i_fu_1011_p2);

assign p_shl1_cast_i_i_fu_849_p1 = p_shl1_i_i_fu_842_p3;

assign p_shl1_i_i_fu_842_p3 = {{remPix_reg_1281}, {3'd0}};

assign p_shl_cast_i_i_fu_838_p1 = p_shl_i_i_fu_831_p3;

assign p_shl_i_i_fu_831_p3 = {{remPix_reg_1281}, {5'd0}};

assign remPix_2_fu_823_p3 = ((tmp_5_i_i_fu_818_p2[0:0] === 1'b1) ? 4'd8 : remPix_cast_i_i_fu_815_p1);

assign remPix_cast_i_i_fu_815_p1 = remPix_reg_1281;

assign remPix_fu_788_p1 = HwReg_width_cast6_loc_dout[2:0];

assign remainTrx_fu_875_p3 = ((tmp_5_i_i_fu_818_p2[0:0] === 1'b1) ? 3'd3 : tmp_8_cast_i_i_fu_865_p4);

assign tmp_10_fu_959_p4 = {{remainTrx_fu_875_p3[2:1]}};

assign tmp_10_i_i_fu_886_p2 = ($signed(13'd8191) + $signed(loopWidth_cast_i_i_reg_1289));

assign tmp_11_i_i_fu_1000_p2 = (($signed(x_cast_i_i_fu_996_p1) < $signed(loopWidth_cast_i_i_reg_1289)) ? 1'b1 : 1'b0);

assign tmp_12_i_i_fu_1011_p2 = (($signed(x_cast_i_i_fu_996_p1) < $signed(tmp_10_i_i_reg_1305)) ? 1'b1 : 1'b0);

assign tmp_131_i_i_fu_891_p2 = ((remPix_2_fu_823_p3 != 4'd0) ? 1'b1 : 1'b0);

assign tmp_13_2_i_i_fu_913_p2 = ((remPix_2_fu_823_p3 > 4'd2) ? 1'b1 : 1'b0);

assign tmp_13_4_i_i_fu_935_p2 = ((remPix_2_fu_823_p3 > 4'd4) ? 1'b1 : 1'b0);

assign tmp_13_5_i_i_fu_941_p2 = ((remPix_2_fu_823_p3 > 4'd5) ? 1'b1 : 1'b0);

assign tmp_13_6_i_i_fu_947_p2 = ((remPix_2_fu_823_p3 > 4'd6) ? 1'b1 : 1'b0);

assign tmp_141_i_i_fu_953_p2 = ((remainTrx_fu_875_p3 != 3'd0) ? 1'b1 : 1'b0);

assign tmp_14_2_i_i_fu_975_p2 = ((remainTrx_fu_875_p3 > 3'd2) ? 1'b1 : 1'b0);

assign tmp_1_i_i_fu_696_p2 = ((VideoFormat == 8'd28) ? 1'b1 : 1'b0);

assign tmp_2_cast_i_i_fu_768_p1 = tmp_8_loc_dout;

assign tmp_3_fu_674_p4 = {{VideoFormat_off1_i_i_fu_668_p2[7:1]}};

assign tmp_3_i_i_fu_772_p2 = (17'd7 + tmp_2_cast_i_i_fu_768_p1);

assign tmp_4_fu_708_p4 = {{VideoFormat_off2_i_i_fu_702_p2[7:1]}};

assign tmp_4_i_i_fu_797_p2 = (14'd2 + loopWidth1_cast_i_i_reg_1276);

assign tmp_5_fu_730_p4 = {{VideoFormat_off3_i_i_fu_724_p2[7:1]}};

assign tmp_5_i_i_fu_818_p2 = ((remPix_reg_1281 == 3'd0) ? 1'b1 : 1'b0);

assign tmp_6_fu_752_p4 = {{VideoFormat_off4_i_i_fu_746_p2[7:1]}};

assign tmp_6_i_i_fu_853_p2 = (p_shl_cast_i_i_fu_838_p1 - p_shl1_cast_i_i_fu_849_p1);

assign tmp_7_i_i_fu_859_p2 = (9'd63 + tmp_6_i_i_fu_853_p2);

assign tmp_8_cast_i_i_fu_865_p4 = {{tmp_7_i_i_fu_859_p2[8:6]}};

assign tmp_8_fu_897_p4 = {{remPix_2_fu_823_p3[3:1]}};

assign tmp_8_loc_out_din = tmp_8_loc_dout;

assign tmp_9_cast_i_i_fu_883_p1 = HwReg_height_cast5_l_reg_1215;

assign tmp_9_fu_919_p4 = {{remPix_2_fu_823_p3[3:2]}};

assign tmp_V_1_fu_1094_p9 = {{{{{{{{ap_phi_reg_pp0_iter1_pix_val_V_0_7_i_i_reg_557}, {pix_val_V_2_6_i_i_reg_502}}, {pix_val_V_1_6_i_i_reg_513}}, {pix_val_V_0_6_i_i_reg_524}}, {pix_val_V_2_5_i_i_reg_469}}, {pix_val_V_1_5_i_i_reg_480}}, {pix_val_V_0_5_i_i_reg_491}}, {pix_val_V_2_4_i_i_reg_436}};

assign tmp_V_2_fu_1167_p9 = {{{{{{{{ap_phi_mux_pix_val_V_2_9_i_i_phi_fu_601_p4}, {ap_phi_mux_pix_val_V_1_9_i_i_phi_fu_611_p4}}, {ap_phi_mux_pix_val_V_0_9_i_i_phi_fu_621_p4}}, {ap_phi_reg_pp0_iter1_pix_val_V_2_8_i_i_reg_568}}, {ap_phi_reg_pp0_iter1_pix_val_V_1_8_i_i_reg_578}}, {ap_phi_reg_pp0_iter1_pix_val_V_0_8_i_i_reg_588}}, {pix_val_V_2_7_i_i_reg_535}}, {pix_val_V_1_7_i_i_reg_546}};

assign tmp_V_fu_1073_p9 = {{{{{{{{ap_phi_reg_pp0_iter0_pix_val_V_1_4_i_i_reg_447}, {ap_phi_reg_pp0_iter0_pix_val_V_0_4_i_i_reg_458}}, {pix_val_V_2_3_i_i_reg_403}}, {pix_val_V_1_3_i_i_reg_414}}, {pix_val_V_0_3_i_i_reg_425}}, {pix_val_V_2_2_i_i_reg_373}}, {pix_val_V_1_2_i_i_reg_383}}, {pix_val_V_0_2_i_i_reg_393}};

assign tmp_fu_646_p4 = {{VideoFormat_off_i_i_fu_640_p2[7:1]}};

assign tmp_i_i_219_fu_690_p2 = ((VideoFormat == 8'd12) ? 1'b1 : 1'b0);

assign tmp_i_i_fu_662_p2 = ((VideoFormat == 8'd27) ? 1'b1 : 1'b0);

assign x_cast_i_i_fu_996_p1 = ap_phi_mux_x_i_i_phi_fu_366_p4;

assign x_fu_1005_p2 = (ap_phi_mux_x_i_i_phi_fu_366_p4 + 12'd1);

assign y_cast_i_i_fu_981_p1 = y_i_i_reg_351;

assign y_fu_990_p2 = (y_i_i_reg_351 + 16'd1);

always @ (posedge ap_clk) begin
    tmp_9_cast_i_i_reg_1300[16:11] <= 6'b000000;
end

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes
