// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        img_V_val_0_V_din,
        img_V_val_0_V_full_n,
        img_V_val_0_V_write,
        img_V_val_1_V_din,
        img_V_val_1_V_full_n,
        img_V_val_1_V_write,
        img_V_val_2_V_din,
        img_V_val_2_V_full_n,
        img_V_val_2_V_write,
        HwReg_height_cast5_loc_dout,
        HwReg_height_cast5_loc_empty_n,
        HwReg_height_cast5_loc_read,
        HwReg_width_cast6_loc_dout,
        HwReg_width_cast6_loc_empty_n,
        HwReg_width_cast6_loc_read,
        colorFormat,
        HwReg_height_cast5_loc_out_din,
        HwReg_height_cast5_loc_out_full_n,
        HwReg_height_cast5_loc_out_write,
        HwReg_width_cast6_loc_out_din,
        HwReg_width_cast6_loc_out_full_n,
        HwReg_width_cast6_loc_out_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_pp1_stage0 = 9'd32;
parameter    ap_ST_fsm_state8 = 9'd64;
parameter    ap_ST_fsm_pp2_stage0 = 9'd128;
parameter    ap_ST_fsm_state11 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [7:0] img_V_val_0_V_din;
input   img_V_val_0_V_full_n;
output   img_V_val_0_V_write;
output  [7:0] img_V_val_1_V_din;
input   img_V_val_1_V_full_n;
output   img_V_val_1_V_write;
output  [7:0] img_V_val_2_V_din;
input   img_V_val_2_V_full_n;
output   img_V_val_2_V_write;
input  [10:0] HwReg_height_cast5_loc_dout;
input   HwReg_height_cast5_loc_empty_n;
output   HwReg_height_cast5_loc_read;
input  [11:0] HwReg_width_cast6_loc_dout;
input   HwReg_width_cast6_loc_empty_n;
output   HwReg_width_cast6_loc_read;
input  [7:0] colorFormat;
output  [10:0] HwReg_height_cast5_loc_out_din;
input   HwReg_height_cast5_loc_out_full_n;
output   HwReg_height_cast5_loc_out_write;
output  [11:0] HwReg_width_cast6_loc_out_din;
input   HwReg_width_cast6_loc_out_full_n;
output   HwReg_width_cast6_loc_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg HwReg_height_cast5_loc_read;
reg HwReg_width_cast6_loc_read;
reg HwReg_height_cast5_loc_out_write;
reg HwReg_width_cast6_loc_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [23:0] AXI_video_strm_V_data_V_0_data_out;
wire    AXI_video_strm_V_data_V_0_vld_in;
wire    AXI_video_strm_V_data_V_0_vld_out;
wire    AXI_video_strm_V_data_V_0_ack_in;
reg    AXI_video_strm_V_data_V_0_ack_out;
reg   [23:0] AXI_video_strm_V_data_V_0_payload_A;
reg   [23:0] AXI_video_strm_V_data_V_0_payload_B;
reg    AXI_video_strm_V_data_V_0_sel_rd;
reg    AXI_video_strm_V_data_V_0_sel_wr;
wire    AXI_video_strm_V_data_V_0_sel;
wire    AXI_video_strm_V_data_V_0_load_A;
wire    AXI_video_strm_V_data_V_0_load_B;
reg   [1:0] AXI_video_strm_V_data_V_0_state;
wire    AXI_video_strm_V_data_V_0_state_cmp_full;
reg   [0:0] AXI_video_strm_V_user_V_0_data_out;
wire    AXI_video_strm_V_user_V_0_vld_in;
wire    AXI_video_strm_V_user_V_0_vld_out;
wire    AXI_video_strm_V_user_V_0_ack_in;
reg    AXI_video_strm_V_user_V_0_ack_out;
reg   [0:0] AXI_video_strm_V_user_V_0_payload_A;
reg   [0:0] AXI_video_strm_V_user_V_0_payload_B;
reg    AXI_video_strm_V_user_V_0_sel_rd;
reg    AXI_video_strm_V_user_V_0_sel_wr;
wire    AXI_video_strm_V_user_V_0_sel;
wire    AXI_video_strm_V_user_V_0_load_A;
wire    AXI_video_strm_V_user_V_0_load_B;
reg   [1:0] AXI_video_strm_V_user_V_0_state;
wire    AXI_video_strm_V_user_V_0_state_cmp_full;
reg   [0:0] AXI_video_strm_V_last_V_0_data_out;
wire    AXI_video_strm_V_last_V_0_vld_in;
wire    AXI_video_strm_V_last_V_0_vld_out;
wire    AXI_video_strm_V_last_V_0_ack_in;
reg    AXI_video_strm_V_last_V_0_ack_out;
reg   [0:0] AXI_video_strm_V_last_V_0_payload_A;
reg   [0:0] AXI_video_strm_V_last_V_0_payload_B;
reg    AXI_video_strm_V_last_V_0_sel_rd;
reg    AXI_video_strm_V_last_V_0_sel_wr;
wire    AXI_video_strm_V_last_V_0_sel;
wire    AXI_video_strm_V_last_V_0_load_A;
wire    AXI_video_strm_V_last_V_0_load_B;
reg   [1:0] AXI_video_strm_V_last_V_0_state;
wire    AXI_video_strm_V_last_V_0_state_cmp_full;
wire    AXI_video_strm_V_dest_V_0_vld_in;
reg    AXI_video_strm_V_dest_V_0_ack_out;
reg   [1:0] AXI_video_strm_V_dest_V_0_state;
reg    s_axis_video_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] exitcond6_i_i_reg_588;
reg   [0:0] brmerge_i_i_reg_597;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage0;
reg   [0:0] eol_2_i_i_reg_364;
reg    img_V_val_0_V_blk_n;
reg    img_V_val_1_V_blk_n;
reg    img_V_val_2_V_blk_n;
reg    HwReg_height_cast5_loc_blk_n;
reg    HwReg_width_cast6_loc_blk_n;
reg    HwReg_height_cast5_loc_out_blk_n;
reg    HwReg_width_cast6_loc_out_blk_n;
reg   [0:0] eol_i_i_reg_294;
reg   [11:0] j_i_i_reg_306;
reg   [0:0] eol_reg_317;
reg   [23:0] axi_data_V_1_i_i_reg_328;
reg   [0:0] axi_last_V_3_i_i_reg_375;
reg   [23:0] axi_data_V_3_i_i_reg_387;
reg   [11:0] HwReg_width_cast6_lo_reg_527;
reg    ap_block_state1;
wire   [11:0] Height_cast_i_i_fu_409_p1;
reg   [11:0] Height_cast_i_i_reg_532;
wire    ap_CS_fsm_state2;
wire    grp_reg_unsigned_short_s_fu_413_ap_done;
wire    grp_reg_unsigned_short_s_fu_419_ap_done;
reg    ap_block_state2_on_subcall_done;
wire   [11:0] grp_reg_unsigned_short_s_fu_413_ap_return;
reg   [11:0] tmp_i_i_reg_542;
wire   [11:0] grp_reg_unsigned_short_s_fu_419_ap_return;
reg   [11:0] tmp_i_i_230_reg_547;
reg   [23:0] tmp_data_V_reg_552;
reg   [0:0] tmp_last_V_reg_560;
wire   [0:0] sel_tmp2_fu_429_p2;
reg   [0:0] sel_tmp2_reg_572;
wire    ap_CS_fsm_state4;
wire   [0:0] exitcond5_i_i_fu_443_p2;
wire    ap_CS_fsm_state5;
wire   [10:0] i_fu_448_p2;
reg   [10:0] i_reg_583;
wire   [0:0] exitcond6_i_i_fu_454_p2;
wire    ap_block_state6_pp1_stage0_iter0;
reg    ap_predicate_op80_read_state7;
wire    img_V_val_0_V1_status;
reg    ap_block_state7_pp1_stage0_iter1;
reg    ap_block_pp1_stage0_11001;
wire   [11:0] j_fu_459_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] brmerge_i_i_fu_468_p2;
wire    ap_block_state9_pp2_stage0_iter0;
reg    ap_block_state10_pp2_stage0_iter1;
reg    ap_block_pp2_stage0_11001;
reg    ap_block_pp1_stage0_subdone;
reg    ap_enable_reg_pp2_iter0;
wire    ap_CS_fsm_state8;
reg    ap_block_pp2_stage0_subdone;
reg   [0:0] ap_phi_mux_eol_2_i_i_phi_fu_367_p4;
wire    grp_reg_unsigned_short_s_fu_413_ap_start;
wire    grp_reg_unsigned_short_s_fu_413_ap_idle;
wire    grp_reg_unsigned_short_s_fu_413_ap_ready;
wire    grp_reg_unsigned_short_s_fu_419_ap_start;
wire    grp_reg_unsigned_short_s_fu_419_ap_idle;
wire    grp_reg_unsigned_short_s_fu_419_ap_ready;
reg   [0:0] axi_last_V1_i_i_reg_263;
wire    ap_CS_fsm_state11;
reg   [23:0] axi_data_V1_i_i_reg_273;
reg   [10:0] i_i_i_reg_283;
reg   [0:0] ap_phi_mux_eol_i_i_phi_fu_298_p4;
reg   [0:0] ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
reg   [23:0] ap_phi_mux_p_Val2_s_phi_fu_356_p4;
wire   [0:0] ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339;
wire   [23:0] ap_phi_reg_pp1_iter1_p_Val2_s_reg_352;
reg    ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start;
reg    ap_block_state1_ignore_call21;
reg    ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start;
reg    ap_block_state1_ignore_call22;
reg    img_V_val_0_V1_update;
reg    ap_block_pp1_stage0_01001;
reg   [0:0] sof_1_i_i_fu_194;
wire   [11:0] i_cast_i_i_fu_439_p1;
wire   [7:0] pix_val_2_V_fu_493_p4;
wire   [7:0] pix_val_0_V_fu_479_p4;
wire   [7:0] pix_val_1_V_8_fu_489_p1;
wire   [0:0] tmp_user_V_fu_425_p1;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
reg    ap_condition_511;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 AXI_video_strm_V_data_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_data_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_data_V_0_state = 2'd0;
#0 AXI_video_strm_V_user_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_user_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_user_V_0_state = 2'd0;
#0 AXI_video_strm_V_last_V_0_sel_rd = 1'b0;
#0 AXI_video_strm_V_last_V_0_sel_wr = 1'b0;
#0 AXI_video_strm_V_last_V_0_state = 2'd0;
#0 AXI_video_strm_V_dest_V_0_state = 2'd0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start = 1'b0;
#0 ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start = 1'b0;
end

design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_413(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_413_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_413_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_413_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_413_ap_ready),
    .in_r(Height_cast_i_i_reg_532),
    .ap_return(grp_reg_unsigned_short_s_fu_413_ap_return)
);

design_1_v_frmbuf_wr_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_419(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_s_fu_419_ap_start),
    .ap_done(grp_reg_unsigned_short_s_fu_419_ap_done),
    .ap_idle(grp_reg_unsigned_short_s_fu_419_ap_idle),
    .ap_ready(grp_reg_unsigned_short_s_fu_419_ap_ready),
    .in_r(HwReg_width_cast6_lo_reg_527),
    .ap_return(grp_reg_unsigned_short_s_fu_419_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_out))) begin
            AXI_video_strm_V_data_V_0_sel_rd <= ~AXI_video_strm_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_data_V_0_ack_in) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in))) begin
            AXI_video_strm_V_data_V_0_sel_wr <= ~AXI_video_strm_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((AXI_video_strm_V_data_V_0_state == 2'd2) & (1'b0 == AXI_video_strm_V_data_V_0_vld_in)) | ((AXI_video_strm_V_data_V_0_state == 2'd3) & (1'b0 == AXI_video_strm_V_data_V_0_vld_in) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd2;
        end else if ((((AXI_video_strm_V_data_V_0_state == 2'd1) & (1'b0 == AXI_video_strm_V_data_V_0_ack_out)) | ((AXI_video_strm_V_data_V_0_state == 2'd3) & (1'b0 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_data_V_0_vld_in) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_data_V_0_ack_out) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)) & (AXI_video_strm_V_data_V_0_state == 2'd3)) | ((AXI_video_strm_V_data_V_0_state == 2'd1) & (1'b1 == AXI_video_strm_V_data_V_0_ack_out)) | ((AXI_video_strm_V_data_V_0_state == 2'd2) & (1'b1 == AXI_video_strm_V_data_V_0_vld_in)))) begin
            AXI_video_strm_V_data_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_dest_V_0_state) & (1'b0 == AXI_video_strm_V_dest_V_0_ack_out) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_dest_V_0_vld_in) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_dest_V_0_ack_out) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_dest_V_0_state)) | ((2'd1 == AXI_video_strm_V_dest_V_0_state) & (1'b1 == AXI_video_strm_V_dest_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_dest_V_0_state) & (1'b1 == AXI_video_strm_V_dest_V_0_vld_in)))) begin
            AXI_video_strm_V_dest_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_out))) begin
            AXI_video_strm_V_last_V_0_sel_rd <= ~AXI_video_strm_V_last_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_last_V_0_ack_in) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in))) begin
            AXI_video_strm_V_last_V_0_sel_wr <= ~AXI_video_strm_V_last_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_vld_in) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_last_V_0_state) & (1'b0 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_last_V_0_vld_in) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_last_V_0_ack_out) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_last_V_0_state)) | ((2'd1 == AXI_video_strm_V_last_V_0_state) & (1'b1 == AXI_video_strm_V_last_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_last_V_0_state) & (1'b1 == AXI_video_strm_V_last_V_0_vld_in)))) begin
            AXI_video_strm_V_last_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_out))) begin
            AXI_video_strm_V_user_V_0_sel_rd <= ~AXI_video_strm_V_user_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == AXI_video_strm_V_user_V_0_ack_in) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in))) begin
            AXI_video_strm_V_user_V_0_sel_wr <= ~AXI_video_strm_V_user_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        AXI_video_strm_V_user_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_vld_in)) | ((2'd3 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_vld_in) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd2;
        end else if ((((2'd1 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_ack_out)) | ((2'd3 == AXI_video_strm_V_user_V_0_state) & (1'b0 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd1;
        end else if (((~((1'b0 == AXI_video_strm_V_user_V_0_vld_in) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)) & ~((1'b0 == AXI_video_strm_V_user_V_0_ack_out) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)) & (2'd3 == AXI_video_strm_V_user_V_0_state)) | ((2'd1 == AXI_video_strm_V_user_V_0_state) & (1'b1 == AXI_video_strm_V_user_V_0_ack_out)) | ((2'd2 == AXI_video_strm_V_user_V_0_state) & (1'b1 == AXI_video_strm_V_user_V_0_vld_in)))) begin
            AXI_video_strm_V_user_V_0_state <= 2'd3;
        end else begin
            AXI_video_strm_V_user_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'd1 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((ap_block_pp1_stage0_subdone == 1'b0) & (1'd1 == exitcond6_i_i_fu_454_p2) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp1_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((ap_block_pp2_stage0_subdone == 1'b0) & (1'd1 == ap_phi_mux_eol_2_i_i_phi_fu_367_p4) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp2_stage0_subdone == 1'b0)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= 1'b0;
    end else begin
        if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= 1'b1;
        end else if ((1'b1 == grp_reg_unsigned_short_s_fu_413_ap_ready)) begin
            ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= 1'b0;
    end else begin
        if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= 1'b1;
        end else if ((1'b1 == grp_reg_unsigned_short_s_fu_419_ap_ready)) begin
            ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_data_V1_i_i_reg_273 <= tmp_data_V_reg_552;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        axi_data_V1_i_i_reg_273 <= axi_data_V_3_i_i_reg_387;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_reg_588) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        axi_data_V_1_i_i_reg_328 <= ap_phi_mux_p_Val2_s_phi_fu_356_p4;
    end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        axi_data_V_1_i_i_reg_328 <= axi_data_V1_i_i_reg_273;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        axi_data_V_3_i_i_reg_387 <= axi_data_V_1_i_i_reg_328;
    end else if (((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        axi_data_V_3_i_i_reg_387 <= AXI_video_strm_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V1_i_i_reg_263 <= tmp_last_V_reg_560;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        axi_last_V1_i_i_reg_263 <= axi_last_V_3_i_i_reg_375;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        axi_last_V_3_i_i_reg_375 <= eol_reg_317;
    end else if (((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        axi_last_V_3_i_i_reg_375 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        eol_2_i_i_reg_364 <= eol_i_i_reg_294;
    end else if (((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        eol_2_i_i_reg_364 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_reg_588) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        eol_i_i_reg_294 <= ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
    end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        eol_i_i_reg_294 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_reg_588) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        eol_reg_317 <= ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
    end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        eol_reg_317 <= axi_last_V1_i_i_reg_263;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_i_i_reg_283 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_i_i_reg_283 <= i_reg_583;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_fu_454_p2) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        j_i_i_reg_306 <= j_fu_459_p2;
    end else if (((1'd0 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        j_i_i_reg_306 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_fu_454_p2) & (1'b1 == ap_enable_reg_pp1_iter0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        sof_1_i_i_fu_194 <= 1'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_1_i_i_fu_194 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_load_A)) begin
        AXI_video_strm_V_data_V_0_payload_A <= s_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_load_B)) begin
        AXI_video_strm_V_data_V_0_payload_B <= s_axis_video_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_load_A)) begin
        AXI_video_strm_V_last_V_0_payload_A <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_load_B)) begin
        AXI_video_strm_V_last_V_0_payload_B <= s_axis_video_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_load_A)) begin
        AXI_video_strm_V_user_V_0_payload_A <= s_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_load_B)) begin
        AXI_video_strm_V_user_V_0_payload_B <= s_axis_video_TUSER;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_cast_i_i_reg_532[10 : 0] <= Height_cast_i_i_fu_409_p1[10 : 0];
        HwReg_width_cast6_lo_reg_527 <= HwReg_width_cast6_loc_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_fu_454_p2) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        brmerge_i_i_reg_597 <= brmerge_i_i_fu_468_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond6_i_i_reg_588 <= exitcond6_i_i_fu_454_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_583 <= i_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sel_tmp2_reg_572 <= sel_tmp2_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_reg_552 <= AXI_video_strm_V_data_V_0_data_out;
        tmp_last_V_reg_560 <= AXI_video_strm_V_last_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_state2_on_subcall_done == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_i_i_230_reg_547 <= grp_reg_unsigned_short_s_fu_419_ap_return;
        tmp_i_i_reg_542 <= grp_reg_unsigned_short_s_fu_413_ap_return;
    end
end

always @ (*) begin
    if ((((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_block_pp1_stage0_11001 == 1'b0) & (1'b1 == ap_predicate_op80_read_state7) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_data_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_data_V_0_sel)) begin
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_B;
    end else begin
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_block_pp1_stage0_11001 == 1'b0) & (1'b1 == ap_predicate_op80_read_state7) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_dest_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_block_pp1_stage0_11001 == 1'b0) & (1'b1 == ap_predicate_op80_read_state7) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_last_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_last_V_0_sel)) begin
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_B;
    end else begin
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_A;
    end
end

always @ (*) begin
    if ((((ap_block_pp2_stage0_11001 == 1'b0) & (1'd0 == eol_2_i_i_reg_364) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_block_pp1_stage0_11001 == 1'b0) & (1'b1 == ap_predicate_op80_read_state7) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        AXI_video_strm_V_user_V_0_ack_out = 1'b1;
    end else begin
        AXI_video_strm_V_user_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == AXI_video_strm_V_user_V_0_sel)) begin
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_B;
    end else begin
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_A;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_blk_n = HwReg_height_cast5_loc_empty_n;
    end else begin
        HwReg_height_cast5_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_blk_n = HwReg_height_cast5_loc_out_full_n;
    end else begin
        HwReg_height_cast5_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_out_write = 1'b1;
    end else begin
        HwReg_height_cast5_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_height_cast5_loc_read = 1'b1;
    end else begin
        HwReg_height_cast5_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_blk_n = HwReg_width_cast6_loc_empty_n;
    end else begin
        HwReg_width_cast6_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_out_blk_n = HwReg_width_cast6_loc_out_full_n;
    end else begin
        HwReg_width_cast6_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_out_write = 1'b1;
    end else begin
        HwReg_width_cast6_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_width_cast6_loc_read = 1'b1;
    end else begin
        HwReg_width_cast6_loc_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp1_iter0) & (1'b0 == ap_enable_reg_pp1_iter1))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp2_iter0) & (1'b0 == ap_enable_reg_pp2_iter1))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_condition_511 == 1'b1)) begin
        if ((1'd1 == brmerge_i_i_reg_597)) begin
            ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 = eol_reg_317;
        end else if ((1'd0 == brmerge_i_i_reg_597)) begin
            ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 = AXI_video_strm_V_last_V_0_data_out;
        end else begin
            ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 = ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339;
        end
    end else begin
        ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4 = ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339;
    end
end

always @ (*) begin
    if (((1'd0 == eol_2_i_i_reg_364) & (ap_block_pp2_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_eol_2_i_i_phi_fu_367_p4 = AXI_video_strm_V_last_V_0_data_out;
    end else begin
        ap_phi_mux_eol_2_i_i_phi_fu_367_p4 = eol_2_i_i_reg_364;
    end
end

always @ (*) begin
    if (((1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_eol_i_i_phi_fu_298_p4 = ap_phi_mux_axi_last_V_2_i_i_phi_fu_344_p4;
    end else begin
        ap_phi_mux_eol_i_i_phi_fu_298_p4 = eol_i_i_reg_294;
    end
end

always @ (*) begin
    if ((ap_condition_511 == 1'b1)) begin
        if ((1'd1 == brmerge_i_i_reg_597)) begin
            ap_phi_mux_p_Val2_s_phi_fu_356_p4 = axi_data_V_1_i_i_reg_328;
        end else if ((1'd0 == brmerge_i_i_reg_597)) begin
            ap_phi_mux_p_Val2_s_phi_fu_356_p4 = AXI_video_strm_V_data_V_0_data_out;
        end else begin
            ap_phi_mux_p_Val2_s_phi_fu_356_p4 = ap_phi_reg_pp1_iter1_p_Val2_s_reg_352;
        end
    end else begin
        ap_phi_mux_p_Val2_s_phi_fu_356_p4 = ap_phi_reg_pp1_iter1_p_Val2_s_reg_352;
    end
end

always @ (*) begin
    if (((1'd1 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp1_stage0_11001 == 1'b0) & (1'd0 == exitcond6_i_i_reg_588) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_0_V1_update = 1'b1;
    end else begin
        img_V_val_0_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_0_V_blk_n = img_V_val_0_V_full_n;
    end else begin
        img_V_val_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_1_V_blk_n = img_V_val_1_V_full_n;
    end else begin
        img_V_val_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        img_V_val_2_V_blk_n = img_V_val_2_V_full_n;
    end else begin
        img_V_val_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((1'd0 == eol_2_i_i_reg_364) & (ap_block_pp2_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'd0 == brmerge_i_i_reg_597) & (1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        s_axis_video_TDATA_blk_n = AXI_video_strm_V_data_V_0_state[1'd0];
    end else begin
        s_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((ap_block_state2_on_subcall_done == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'd0 == tmp_user_V_fu_425_p1) & (AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((1'd1 == tmp_user_V_fu_425_p1) & (AXI_video_strm_V_data_V_0_vld_out == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'd1 == exitcond5_i_i_fu_443_p2) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((ap_block_pp1_stage0_subdone == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((ap_block_pp1_stage0_subdone == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((ap_block_pp2_stage0_subdone == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_block_pp2_stage0_subdone == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (1'b1 == ap_enable_reg_pp2_iter1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AXI_video_strm_V_data_V_0_ack_in = AXI_video_strm_V_data_V_0_state[1'd1];

assign AXI_video_strm_V_data_V_0_load_A = (~AXI_video_strm_V_data_V_0_sel_wr & AXI_video_strm_V_data_V_0_state_cmp_full);

assign AXI_video_strm_V_data_V_0_load_B = (AXI_video_strm_V_data_V_0_state_cmp_full & AXI_video_strm_V_data_V_0_sel_wr);

assign AXI_video_strm_V_data_V_0_sel = AXI_video_strm_V_data_V_0_sel_rd;

assign AXI_video_strm_V_data_V_0_state_cmp_full = ((AXI_video_strm_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_data_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_data_V_0_vld_out = AXI_video_strm_V_data_V_0_state[1'd0];

assign AXI_video_strm_V_dest_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_last_V_0_ack_in = AXI_video_strm_V_last_V_0_state[1'd1];

assign AXI_video_strm_V_last_V_0_load_A = (~AXI_video_strm_V_last_V_0_sel_wr & AXI_video_strm_V_last_V_0_state_cmp_full);

assign AXI_video_strm_V_last_V_0_load_B = (AXI_video_strm_V_last_V_0_state_cmp_full & AXI_video_strm_V_last_V_0_sel_wr);

assign AXI_video_strm_V_last_V_0_sel = AXI_video_strm_V_last_V_0_sel_rd;

assign AXI_video_strm_V_last_V_0_state_cmp_full = ((AXI_video_strm_V_last_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_last_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_last_V_0_vld_out = AXI_video_strm_V_last_V_0_state[1'd0];

assign AXI_video_strm_V_user_V_0_ack_in = AXI_video_strm_V_user_V_0_state[1'd1];

assign AXI_video_strm_V_user_V_0_load_A = (~AXI_video_strm_V_user_V_0_sel_wr & AXI_video_strm_V_user_V_0_state_cmp_full);

assign AXI_video_strm_V_user_V_0_load_B = (AXI_video_strm_V_user_V_0_state_cmp_full & AXI_video_strm_V_user_V_0_sel_wr);

assign AXI_video_strm_V_user_V_0_sel = AXI_video_strm_V_user_V_0_sel_rd;

assign AXI_video_strm_V_user_V_0_state_cmp_full = ((AXI_video_strm_V_user_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign AXI_video_strm_V_user_V_0_vld_in = s_axis_video_TVALID;

assign AXI_video_strm_V_user_V_0_vld_out = AXI_video_strm_V_user_V_0_state[1'd0];

assign Height_cast_i_i_fu_409_p1 = HwReg_height_cast5_loc_dout;

assign HwReg_height_cast5_loc_out_din = HwReg_height_cast5_loc_dout;

assign HwReg_width_cast6_loc_out_din = HwReg_width_cast6_loc_dout;

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((1'b1 == ap_enable_reg_pp1_iter1) & (((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_predicate_op80_read_state7)) | ((1'd0 == exitcond6_i_i_reg_588) & (1'b0 == img_V_val_0_V1_status))));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((1'b1 == ap_enable_reg_pp1_iter1) & (((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_predicate_op80_read_state7)) | ((1'd0 == exitcond6_i_i_reg_588) & (1'b0 == img_V_val_0_V1_status))));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((1'b1 == ap_enable_reg_pp1_iter1) & (((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_predicate_op80_read_state7)) | ((1'd0 == exitcond6_i_i_reg_588) & (1'b0 == img_V_val_0_V1_status))));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((1'd0 == eol_2_i_i_reg_364) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_enable_reg_pp2_iter1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((1'd0 == eol_2_i_i_reg_364) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_enable_reg_pp2_iter1));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state10_pp2_stage0_iter1 = ((1'd0 == eol_2_i_i_reg_364) & (1'b0 == AXI_video_strm_V_data_V_0_vld_out));
end

always @ (*) begin
    ap_block_state1_ignore_call21 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call22 = ((1'b0 == HwReg_width_cast6_loc_out_full_n) | (1'b0 == HwReg_height_cast5_loc_out_full_n) | (1'b0 == HwReg_width_cast6_loc_empty_n) | (1'b0 == HwReg_height_cast5_loc_empty_n) | (1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((1'b0 == grp_reg_unsigned_short_s_fu_419_ap_done) | (1'b0 == grp_reg_unsigned_short_s_fu_413_ap_done));
end

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp1_stage0_iter1 = (((1'b0 == AXI_video_strm_V_data_V_0_vld_out) & (1'b1 == ap_predicate_op80_read_state7)) | ((1'd0 == exitcond6_i_i_reg_588) & (1'b0 == img_V_val_0_V1_status)));
end

assign ap_block_state9_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_511 = ((1'd0 == exitcond6_i_i_reg_588) & (ap_block_pp1_stage0 == 1'b0) & (1'b1 == ap_enable_reg_pp1_iter1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_phi_reg_pp1_iter1_axi_last_V_2_i_i_reg_339 = 'bx;

assign ap_phi_reg_pp1_iter1_p_Val2_s_reg_352 = 'bx;

always @ (*) begin
    ap_predicate_op80_read_state7 = ((1'd0 == brmerge_i_i_reg_597) & (1'd0 == exitcond6_i_i_reg_588));
end

assign brmerge_i_i_fu_468_p2 = (sof_1_i_i_fu_194 | ap_phi_mux_eol_i_i_phi_fu_298_p4);

assign exitcond5_i_i_fu_443_p2 = ((i_cast_i_i_fu_439_p1 == tmp_i_i_reg_542) ? 1'b1 : 1'b0);

assign exitcond6_i_i_fu_454_p2 = ((j_i_i_reg_306 == tmp_i_i_230_reg_547) ? 1'b1 : 1'b0);

assign grp_reg_unsigned_short_s_fu_413_ap_start = ap_reg_grp_reg_unsigned_short_s_fu_413_ap_start;

assign grp_reg_unsigned_short_s_fu_419_ap_start = ap_reg_grp_reg_unsigned_short_s_fu_419_ap_start;

assign i_cast_i_i_fu_439_p1 = i_i_i_reg_283;

assign i_fu_448_p2 = (i_i_i_reg_283 + 11'd1);

assign img_V_val_0_V1_status = (img_V_val_2_V_full_n & img_V_val_1_V_full_n & img_V_val_0_V_full_n);

assign img_V_val_0_V_din = ((sel_tmp2_reg_572[0:0] === 1'b1) ? pix_val_0_V_fu_479_p4 : pix_val_1_V_8_fu_489_p1);

assign img_V_val_0_V_write = img_V_val_0_V1_update;

assign img_V_val_1_V_din = ((sel_tmp2_reg_572[0:0] === 1'b1) ? pix_val_1_V_8_fu_489_p1 : pix_val_2_V_fu_493_p4);

assign img_V_val_1_V_write = img_V_val_0_V1_update;

assign img_V_val_2_V_din = ((sel_tmp2_reg_572[0:0] === 1'b1) ? pix_val_2_V_fu_493_p4 : pix_val_0_V_fu_479_p4);

assign img_V_val_2_V_write = img_V_val_0_V1_update;

assign j_fu_459_p2 = (j_i_i_reg_306 + 12'd1);

assign pix_val_0_V_fu_479_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_356_p4[23:16]}};

assign pix_val_1_V_8_fu_489_p1 = ap_phi_mux_p_Val2_s_phi_fu_356_p4[7:0];

assign pix_val_2_V_fu_493_p4 = {{ap_phi_mux_p_Val2_s_phi_fu_356_p4[15:8]}};

assign s_axis_video_TREADY = AXI_video_strm_V_dest_V_0_state[1'd1];

assign sel_tmp2_fu_429_p2 = ((colorFormat == 8'd0) ? 1'b1 : 1'b0);

assign tmp_user_V_fu_425_p1 = AXI_video_strm_V_user_V_0_data_out;

always @ (posedge ap_clk) begin
    Height_cast_i_i_reg_532[11] <= 1'b0;
end

endmodule //design_1_v_frmbuf_wr_0_0_AXIvideo2MultiPixStr
