variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_NAME: "ThinpadNG_Zynq7"
  VIVADO_PATH: "/opt/Xilinx/Vivado/2018.3/bin/vivado"


# all files in ip dir except *.xci are ignored, so the generated result will be cleaned every build
# to avoid generating from scratch every time, the dir should be cached
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ${PROJECT_NAME}.srcs/sources_1/ip
    - ${PROJECT_NAME}.srcs/sources_1/bd
    - ${PROJECT_NAME}.sim
    - ${PROJECT_NAME}.runs
    - ${PROJECT_NAME}.cache

stages:
  - generate_ip
  - generate_bitstream
  - deploy

out_of_context_module_runs:
  stage: generate_ip
  image: vivado2018:2018.3
  before_script:
    # the cached ip configuration file might be out of date, we should always use the newest one
    - git checkout ${PROJECT_NAME}.srcs/sources_1/bd/*/*.bd
    - find ${PROJECT_NAME}.srcs/sources_1/ip -name '*.xci' -exec git checkout '{}' ';'
  script:
    - echo "CI_JOB_MANUAL=$CI_JOB_MANUAL"
    - ${VIVADO_PATH} -mode tcl -source tools/build_ip.tcl ${PROJECT_NAME}.xpr
  artifacts:
    paths:
      - ${PROJECT_NAME}.runs/*/runme.log

impl_1:
  stage: generate_bitstream
  image: vivado2018:2018.3
  script:
      #- ${VIVADO_PATH} -mode tcl -source tools/build_bitstream.tcl ${PROJECT_NAME}.xpr -tclargs 2
      #- cp ${PROJECT_NAME}.runs/impl_1/thinpadNG_zynq_top.sysdef thinpadNG_zynq_top_rev2.hdf
    - ${VIVADO_PATH} -mode tcl -source tools/build_bitstream.tcl ${PROJECT_NAME}.xpr -tclargs 3
    - cp ${PROJECT_NAME}.runs/impl_1/thinpadNG_zynq_top.sysdef thinpadNG_zynq_top_rev3.hdf
  artifacts:
    paths:
        #- thinpadNG_zynq_top_rev2.hdf
      - thinpadNG_zynq_top_rev3.hdf
      - ${PROJECT_NAME}.runs/synth_1/runme.log
      - ${PROJECT_NAME}.runs/impl_1/runme.log
    when: always

trigger_build:
  stage: deploy
  image: sequenceiq/alpine-curl
  script:
    - "curl -X POST -F token=ce4b02c88036d1763787326d0b281b -F ref=petalinux1603 https://git.tsinghua.edu.cn/api/v4/projects/359/trigger/pipeline"


