variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PROJECT_NAME: "ThinpadNG_Zynq7"
  VIVADO_PATH: "/opt/Xilinx/Vivado/2017.3/bin/vivado"


# all files in ip dir except *.xci are ignored, so the generated result will be cleaned every build
# to avoid generating from scratch every time, the dir should be cached
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - ${PROJECT_NAME}.srcs/sources_1/ip
    - ${PROJECT_NAME}.srcs/sources_1/bd
    - ${PROJECT_NAME}.sim
    - ${PROJECT_NAME}.runs
    - ${PROJECT_NAME}.cache

stages:
  - generate_ip
  - generate_bitstream

out_of_context_module_runs:
  stage: generate_ip
  image: vivado2017:2017.3
  before_script:
    # the cached ip configuration file might be out of date, we should always use the newest one
    - git checkout ${PROJECT_NAME}.srcs/sources_1/bd/*/*.bd
    - find ${PROJECT_NAME}.srcs/sources_1/ip -name '*.xci' -exec git checkout '{}' ';'
  script:
    - ${VIVADO_PATH} -mode tcl -source tools/build_ip.tcl ${PROJECT_NAME}.xpr
  artifacts:
    paths:
      - ${PROJECT_NAME}.runs/*/runme.log

impl_1:
  stage: generate_bitstream
  image: vivado2017:2017.3
  script:
    - ${VIVADO_PATH} -mode tcl -source tools/build_bitstream.tcl ${PROJECT_NAME}.xpr
  artifacts:
    paths:
      - ${PROJECT_NAME}.runs/impl_1/thinpadNG_zynq_top.bit
      - ${PROJECT_NAME}.runs/impl_1/runme.log
    when: always



