#create_generated_clock -name clk_uart16x -source [get_pins uart_clk/inst/mmcm_adv_inst/CLKOUT0] -divide_by 36 [get_pins cpld_emu/u3/clk_reg/Q]
create_clock -period 8.620 -name clkin1_p -waveform {0.000 3.690} [get_ports clkin1_p]

set_property PACKAGE_PIN Y6 [get_ports clk_out1]
set_property PACKAGE_PIN Y5 [get_ports clk_out2]

set_property PACKAGE_PIN V18 [get_ports UART_1_rxd]
set_property PACKAGE_PIN V13 [get_ports UART_1_txd]

set_property PACKAGE_PIN T17 [get_ports SPI0_MOSI_O]
set_property PACKAGE_PIN R19 [get_ports SPI0_SCLK_O]

set_property PACKAGE_PIN T19 [get_ports {progb[0]}]
set_property PACKAGE_PIN N17 [get_ports initb]
set_property PACKAGE_PIN P18 [get_ports done]
set_property -dict {PACKAGE_PIN AA7 IOSTANDARD LVCMOS33} [get_ports tap_tck]
set_property -dict {PACKAGE_PIN AB11 IOSTANDARD LVCMOS33} [get_ports tap_tms]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS33} [get_ports tap_tdi]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD LVCMOS33} [get_ports tap_tdo]

set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports dvi_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {dvi_clk_IBUF}]

set_property -dict {PACKAGE_PIN AA16 IOSTANDARD LVCMOS33} [get_ports dvi_hs]
set_property -dict {PACKAGE_PIN AB16 IOSTANDARD LVCMOS33} [get_ports dvi_vs]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS33} [get_ports dvi_de]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD LVCMOS33} [get_ports dvi_d[0]]
set_property -dict {PACKAGE_PIN AB9 IOSTANDARD LVCMOS33} [get_ports dvi_d[1]]
set_property -dict {PACKAGE_PIN U10 IOSTANDARD LVCMOS33} [get_ports dvi_d[2]]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS33} [get_ports dvi_d[3]]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS33} [get_ports dvi_d[4]]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports dvi_d[5]]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports dvi_d[6]]
set_property -dict {PACKAGE_PIN AB10 IOSTANDARD LVCMOS33} [get_ports dvi_d[7]]

# GPIOs
# leds
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_rtl_tri_io[31]}]

set_property PACKAGE_PIN Y15 [get_ports {gpio_rtl_tri_io[0]}]
set_property PACKAGE_PIN Y14 [get_ports {gpio_rtl_tri_io[1]}]
set_property PACKAGE_PIN W12 [get_ports {gpio_rtl_tri_io[2]}]
set_property PACKAGE_PIN Y16 [get_ports {gpio_rtl_tri_io[3]}]
set_property PACKAGE_PIN Y20 [get_ports {gpio_rtl_tri_io[4]}]
set_property PACKAGE_PIN Y18 [get_ports {gpio_rtl_tri_io[5]}]
set_property PACKAGE_PIN W18 [get_ports {gpio_rtl_tri_io[6]}]
set_property PACKAGE_PIN U19 [get_ports {gpio_rtl_tri_io[7]}]
set_property PACKAGE_PIN Y11 [get_ports {gpio_rtl_tri_io[8]}]
set_property PACKAGE_PIN V10 [get_ports {gpio_rtl_tri_io[9]}]
set_property PACKAGE_PIN V12 [get_ports {gpio_rtl_tri_io[10]}]
set_property PACKAGE_PIN W15 [get_ports {gpio_rtl_tri_io[11]}]
set_property PACKAGE_PIN Y19 [get_ports {gpio_rtl_tri_io[12]}]
set_property PACKAGE_PIN W17 [get_ports {gpio_rtl_tri_io[13]}]
set_property PACKAGE_PIN W10 [get_ports {gpio_rtl_tri_io[14]}]
set_property PACKAGE_PIN V9 [get_ports {gpio_rtl_tri_io[15]}]
set_property PACKAGE_PIN AA17 [get_ports {gpio_rtl_tri_io[16]}]
set_property PACKAGE_PIN AB17 [get_ports {gpio_rtl_tri_io[17]}]
set_property PACKAGE_PIN AA18 [get_ports {gpio_rtl_tri_io[18]}]
set_property PACKAGE_PIN AB19 [get_ports {gpio_rtl_tri_io[19]}]
set_property PACKAGE_PIN AB1 [get_ports {gpio_rtl_tri_io[20]}]
set_property PACKAGE_PIN AB2 [get_ports {gpio_rtl_tri_io[21]}]
set_property PACKAGE_PIN W5 [get_ports {gpio_rtl_tri_io[22]}]
set_property PACKAGE_PIN AB4 [get_ports {gpio_rtl_tri_io[23]}]
set_property PACKAGE_PIN AB22 [get_ports {gpio_rtl_tri_io[24]}]
set_property PACKAGE_PIN AA22 [get_ports {gpio_rtl_tri_io[25]}]
set_property PACKAGE_PIN Y21 [get_ports {gpio_rtl_tri_io[26]}]
set_property PACKAGE_PIN W21 [get_ports {gpio_rtl_tri_io[27]}]
set_property PACKAGE_PIN AA19 [get_ports {gpio_rtl_tri_io[28]}]
set_property PACKAGE_PIN AB20 [get_ports {gpio_rtl_tri_io[29]}]
set_property PACKAGE_PIN AB21 [get_ports {gpio_rtl_tri_io[30]}]
set_property PACKAGE_PIN AA21 [get_ports {gpio_rtl_tri_io[31]}]
#switches
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[0]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[1]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[2]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[3]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[4]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[5]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[6]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[7]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[8]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[9]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[10]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[11]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[12]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[13]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[14]}]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[15]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[16]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[17]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[18]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[19]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[20]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[21]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[22]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[23]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[24]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[25]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[26]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[27]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[28]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[29]}]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[30]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_1_tri_io[31]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[1]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[2]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[3]}]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[4]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33 PULLDOWN true } [get_ports {gpio_rtl_0_tri_io[5]}]

# base sram
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_addr_wrap[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_dq_io[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_ce_n_wrap[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_oen_wrap[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports emc_rtl_wen_wrap]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_ben_wrap[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_ben_wrap[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_ben_wrap[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {emc_rtl_ben_wrap[3]}]

set_property PACKAGE_PIN K20 [get_ports {emc_rtl_addr_wrap[0]}]
set_property PACKAGE_PIN J18 [get_ports {emc_rtl_addr_wrap[1]}]
set_property PACKAGE_PIN J20 [get_ports {emc_rtl_addr_wrap[2]}]
set_property PACKAGE_PIN H19 [get_ports {emc_rtl_addr_wrap[3]}]
set_property PACKAGE_PIN H20 [get_ports {emc_rtl_addr_wrap[4]}]
set_property PACKAGE_PIN R21 [get_ports {emc_rtl_addr_wrap[5]}]
set_property PACKAGE_PIN R20 [get_ports {emc_rtl_addr_wrap[6]}]
set_property PACKAGE_PIN R15 [get_ports {emc_rtl_addr_wrap[7]}]
set_property PACKAGE_PIN T16 [get_ports {emc_rtl_addr_wrap[8]}]
set_property PACKAGE_PIN T22 [get_ports {emc_rtl_addr_wrap[9]}]
set_property PACKAGE_PIN T21 [get_ports {emc_rtl_addr_wrap[10]}]
set_property PACKAGE_PIN U22 [get_ports {emc_rtl_addr_wrap[11]}]
set_property PACKAGE_PIN U21 [get_ports {emc_rtl_addr_wrap[12]}]
set_property PACKAGE_PIN V22 [get_ports {emc_rtl_addr_wrap[13]}]
set_property PACKAGE_PIN W22 [get_ports {emc_rtl_addr_wrap[14]}]
set_property PACKAGE_PIN G17 [get_ports {emc_rtl_addr_wrap[15]}]
set_property PACKAGE_PIN G20 [get_ports {emc_rtl_addr_wrap[16]}]
set_property PACKAGE_PIN G15 [get_ports {emc_rtl_addr_wrap[17]}]
set_property PACKAGE_PIN F19 [get_ports {emc_rtl_addr_wrap[18]}]
set_property PACKAGE_PIN E20 [get_ports {emc_rtl_addr_wrap[19]}]
set_property PACKAGE_PIN D22 [get_ports {emc_rtl_dq_io[0]}]
set_property PACKAGE_PIN D21 [get_ports {emc_rtl_dq_io[1]}]
set_property PACKAGE_PIN C22 [get_ports {emc_rtl_dq_io[2]}]
set_property PACKAGE_PIN B22 [get_ports {emc_rtl_dq_io[3]}]
set_property PACKAGE_PIN A22 [get_ports {emc_rtl_dq_io[4]}]
set_property PACKAGE_PIN B21 [get_ports {emc_rtl_dq_io[5]}]
set_property PACKAGE_PIN A21 [get_ports {emc_rtl_dq_io[6]}]
set_property PACKAGE_PIN B20 [get_ports {emc_rtl_dq_io[7]}]
set_property PACKAGE_PIN P21 [get_ports {emc_rtl_dq_io[8]}]
set_property PACKAGE_PIN P22 [get_ports {emc_rtl_dq_io[9]}]
set_property PACKAGE_PIN N22 [get_ports {emc_rtl_dq_io[10]}]
set_property PACKAGE_PIN M22 [get_ports {emc_rtl_dq_io[11]}]
set_property PACKAGE_PIN M21 [get_ports {emc_rtl_dq_io[12]}]
set_property PACKAGE_PIN L22 [get_ports {emc_rtl_dq_io[13]}]
set_property PACKAGE_PIN L21 [get_ports {emc_rtl_dq_io[14]}]
set_property PACKAGE_PIN K21 [get_ports {emc_rtl_dq_io[15]}]
set_property PACKAGE_PIN J22 [get_ports {emc_rtl_dq_io[16]}]
set_property PACKAGE_PIN J21 [get_ports {emc_rtl_dq_io[17]}]
set_property PACKAGE_PIN H22 [get_ports {emc_rtl_dq_io[18]}]
set_property PACKAGE_PIN G22 [get_ports {emc_rtl_dq_io[19]}]
set_property PACKAGE_PIN G21 [get_ports {emc_rtl_dq_io[20]}]
set_property PACKAGE_PIN F22 [get_ports {emc_rtl_dq_io[21]}]
set_property PACKAGE_PIN F21 [get_ports {emc_rtl_dq_io[22]}]
set_property PACKAGE_PIN E21 [get_ports {emc_rtl_dq_io[23]}]
set_property PACKAGE_PIN P15 [get_ports {emc_rtl_dq_io[24]}]
set_property PACKAGE_PIN P20 [get_ports {emc_rtl_dq_io[25]}]
set_property PACKAGE_PIN N18 [get_ports {emc_rtl_dq_io[26]}]
set_property PACKAGE_PIN P16 [get_ports {emc_rtl_dq_io[27]}]
set_property PACKAGE_PIN N15 [get_ports {emc_rtl_dq_io[28]}]
set_property PACKAGE_PIN M20 [get_ports {emc_rtl_dq_io[29]}]
set_property PACKAGE_PIN M17 [get_ports {emc_rtl_dq_io[30]}]
set_property PACKAGE_PIN M16 [get_ports {emc_rtl_dq_io[31]}]
set_property PACKAGE_PIN F17 [get_ports {emc_rtl_ce_n_wrap[0]}]
set_property PACKAGE_PIN V17 [get_ports {emc_rtl_oen_wrap[0]}]
set_property PACKAGE_PIN F18 [get_ports emc_rtl_wen_wrap]
set_property PACKAGE_PIN V19 [get_ports {emc_rtl_ben_wrap[0]}]
set_property PACKAGE_PIN W20 [get_ports {emc_rtl_ben_wrap[1]}]
set_property PACKAGE_PIN M15 [get_ports {emc_rtl_ben_wrap[2]}]
set_property PACKAGE_PIN L17 [get_ports {emc_rtl_ben_wrap[3]}]


# others
set_property IOSTANDARD LVCMOS33 [get_ports clk_out1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out2]

set_property IOSTANDARD LVCMOS33 [get_ports UART_1_rxd]
set_property PULLUP true [get_ports UART_1_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_1_txd]

set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MOSI_O]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SCLK_O]

set_property IOSTANDARD LVCMOS33 [get_ports {progb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports initb]
set_property IOSTANDARD LVCMOS33 [get_ports done]

